(function(){var aa="_imgFileNameError",ba="_imgUrlTextError",ca="about:invalid#zClosurez",da="allHolder",ea="aria-expanded",fa="bgresponse",ha="chooseWidget",ia="commentBodyField",e="complete",ja="displayModeLayout",ka="displayModeNone",h="div",la="encodedSelectedId",m="function",ma="goog-zippy-collapsed",na="goog-zippy-expanded",oa="hidden",pa="identity-type-",qa="identityHolder",ra="identityMenu",sa="input",ta="keypress",ua="layout-widget-description",va="layout-widget-title",wa="main-status-holder",xa="nameUrlIdentityHolder",
n="none",ya="number",p="object",za="postCommentSubmit",Aa="ready",Ba="rotate(-45deg)",Ca="sectionWidth",Da="select-multiple",Ea="showPreview",Fa="status-message",Ga="status-message-inner",Ha="subscribeButtonHolder",Ia="success",Ja="true",r,Ka=typeof Object.defineProperties==m?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},La="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,Ma=function(){Ma=function(){};
La.Symbol||(La.Symbol=Na)},Na=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}(),Pa=function(){Ma();var a=La.Symbol.iterator;a||(a=La.Symbol.iterator=La.Symbol("iterator"));typeof Array.prototype[a]!=m&&Ka(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return Oa(this)}});Pa=function(){}},Oa=function(a){var b=0;return Qa(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})},Qa=function(a){Pa();a={next:a};a[La.Symbol.iterator]=function(){return this};
return a},Ra=Ra||{},t=this,u=function(a){return void 0!==a},v=function(a){return"string"==typeof a},w=function(a,b,c){a=a.split(".");c=c||t;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&u(b)?c[d]=b:c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}},Sa=/^[\w+/_-]+[=]{0,2}$/,Ta=null,Ua=function(){},Va=function(a){a.uc=void 0;a.lg=function(){return a.uc?a.uc:a.uc=new a}},Wa=function(a){var b=typeof a;if(b==p)if(a){if(a instanceof Array)return"array";
if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return p;if("[object Array]"==c||typeof a.length==ya&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return m}else return"null";else if(b==m&&"undefined"==typeof a.call)return p;return b},x=function(a){return"array"==
Wa(a)},Xa=function(a){var b=Wa(a);return"array"==b||b==p&&typeof a.length==ya},Ya=function(a){return Wa(a)==m},Za=function(a){var b=typeof a;return b==p&&null!=a||b==m},$a="closure_uid_"+(1E9*Math.random()>>>0),ab=0,bb=function(a,b,c){return a.call.apply(a.bind,arguments)},cb=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,
arguments)}},y=function(a,b,c){y=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?bb:cb;return y.apply(null,arguments)},db=Date.now||function(){return+new Date},z=function(a,b){function c(){}c.prototype=b.prototype;a.l=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Oh=function(a,c,g){for(var d=Array(arguments.length-2),f=2;f<arguments.length;f++)d[f-2]=arguments[f];return b.prototype[c].apply(a,d)}};var eb;var fb=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(v(a))return v(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},gb=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(v(a))return v(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=
c;c--)if(c in a&&a[c]===b)return c;return-1},hb=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=v(a)?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)},ib=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],g=0,k=v(a)?a.split(""):a,l=0;l<d;l++)if(l in k){var q=k[l];b.call(c,q,l,a)&&(f[g++]=q)}return f},jb=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,
b,c)}:function(a,b,c){for(var d=a.length,f=Array(d),g=v(a)?a.split(""):a,k=0;k<d;k++)k in g&&(f[k]=b.call(c,g[k],k,a));return f},kb=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=v(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a))return!0;return!1},lb=function(a,b,c){a:{for(var d=a.length,f=v(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a)){b=g;break a}b=-1}return 0>b?null:v(a)?a.charAt(b):a[b]},A=function(a,
b){return 0<=fb(a,b)},mb=function(a){if(!x(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0},nb=function(a,b){b=fb(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c},ob=function(a){return Array.prototype.concat.apply([],arguments)},pb=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},qb=function(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var rb=function(a){return a.replace(/(\r\n|\r|\n)+/g," ")},tb=function(a){return a.replace(/\xa0|[ \t]+/g," ")},ub=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Cb=function(a,b){if(b)a=a.replace(vb,"&amp;").replace(wb,"&lt;").replace(xb,"&gt;").replace(yb,"&quot;").replace(zb,"&#39;").replace(Ab,"&#0;");else{if(!Bb.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(vb,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(wb,"&lt;"));-1!=a.indexOf(">")&&
(a=a.replace(xb,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(yb,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(zb,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ab,"&#0;"))}return a},vb=/&/g,wb=/</g,xb=/>/g,yb=/"/g,zb=/'/g,Ab=/\x00/g,Bb=/[\x00&<>"']/,B=function(a,b){return-1!=a.indexOf(b)},Db=function(a,b){return a<b?-1:a>b?1:0};var C;a:{var Eb=t.navigator;if(Eb){var Fb=Eb.userAgent;if(Fb){C=Fb;break a}}C=""};var Gb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Hb=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Ib=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},Jb=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1},Kb=function(a){for(var b in a)return!1;return!0},Lb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Mb=function(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var g=
0;g<Lb.length;g++)c=Lb[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},Nb=function(a){var b=arguments.length;if(1==b&&x(arguments[0]))return Nb.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};var Ob=function(a){Ob[" "](a);return a};Ob[" "]=Ua;var Pb=function(a,b,c,d){d=d?d(b):b;return Object.prototype.hasOwnProperty.call(a,d)?a[d]:a[d]=c(b)};var Qb=B(C,"Opera"),D=B(C,"Trident")||B(C,"MSIE"),Rb=B(C,"Edge"),E=B(C,"Gecko")&&!(B(C.toLowerCase(),"webkit")&&!B(C,"Edge"))&&!(B(C,"Trident")||B(C,"MSIE"))&&!B(C,"Edge"),F=B(C.toLowerCase(),"webkit")&&!B(C,"Edge"),G=B(C,"Macintosh"),Sb=function(){var a=t.document;return a?a.documentMode:void 0},Tb;
a:{var Ub="",Vb=function(){var a=C;if(E)return/rv:([^\);]+)(\)|;)/.exec(a);if(Rb)return/Edge\/([\d\.]+)/.exec(a);if(D)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(F)return/WebKit\/(\S+)/.exec(a);if(Qb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Vb&&(Ub=Vb?Vb[1]:"");if(D){var Wb=Sb();if(null!=Wb&&Wb>parseFloat(Ub)){Tb=String(Wb);break a}}Tb=Ub}
var Xb=Tb,Yb={},Zb=function(a){return Pb(Yb,a,function(){for(var b=0,c=ub(String(Xb)).split("."),d=ub(String(a)).split("."),f=Math.max(c.length,d.length),g=0;0==b&&g<f;g++){var k=c[g]||"",l=d[g]||"";do{k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];l=/(\d*)(\D*)(.*)/.exec(l)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=Db(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||Db(0==k[2].length,0==l[2].length)||Db(k[2],l[2]);k=k[3];l=l[3]}while(0==b)}return 0<=b})},$b;
var ac=t.document;$b=ac&&D?Sb()||("CSS1Compat"==ac.compatMode?parseInt(Xb,10):5):void 0;var bc=!D||9<=Number($b);var cc=function(a){return a};var ec=function(){this.Uc="";this.xf=dc};ec.prototype.ma=!0;ec.prototype.ca=function(){return this.Uc};ec.prototype.toString=function(){return"Const{"+this.Uc+"}"};var dc={};var gc=function(){this.Mc="";this.If=fc};gc.prototype.ma=!0;gc.prototype.ca=function(){return this.Mc};var fc={};var H=function(){this.Jc="";this.wf=hc};H.prototype.ma=!0;H.prototype.ca=function(){return this.Jc};var ic=function(a){if(a instanceof H&&a.constructor===H&&a.wf===hc)return a.Jc;Wa(a);return"type_error:SafeUrl"},jc=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,lc=function(a){if(a instanceof H)return a;a=typeof a==p&&a.ma?a.ca():String(a);jc.test(a)||(a=ca);return kc(a)},hc={},kc=function(a){var b=new H;b.Jc=a;return b};kc("about:blank");var J=function(){this.Lc="";this.vf=mc};J.prototype.ma=!0;var mc={};J.prototype.ca=function(){return this.Lc};J.prototype.Ta=function(a){this.Lc=a;return this};
var nc=(new J).Ta(""),sc=function(a){if(a instanceof H)a='url("'+ic(a).replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';else if(a instanceof ec)a=a instanceof ec&&a.constructor===ec&&a.xf===dc?a.Uc:"type_error:Const";else{a=String(a);var b=a.replace(oc,"$1").replace(pc,"url");if(b=qc.test(b)){for(var c=b=!0,d=0;d<a.length;d++){var f=a.charAt(d);"'"==f&&c?b=!b:'"'==f&&b&&(c=!c)}b=b&&c}a=b?rc(a):"zClosurez"}return a},qc=/^[-,."'%_!# a-zA-Z0-9]+$/,pc=/\b(url\([ \t\n]*)('[ -&(-\[\]-~]*'|"[ !#-\[\]-~]*"|[!#-&*-\[\]-~]*)([ \t\n]*\))/g,
oc=/\b(hsl|hsla|rgb|rgba|matrix|(rotate|scale|translate)(X|Y|Z|3d)?)\([-0-9a-z.%, ]+\)/g,rc=function(a){return a.replace(pc,function(a,c,d,f){var b="";d=d.replace(/^(['"])(.*)\1$/,function(a,c,d){b=c;return d});a=lc(d).ca();return c+b+a+b+f})};var uc=function(){this.Kc="";this.uf=tc};uc.prototype.ma=!0;
var tc={},vc=function(a,b){if(B(a,"<"))throw Error("Selector does not allow '<', got: "+a);var c=a.replace(/('|")((?!\1)[^\r\n\f\\]|\\[\s\S])*\1/g,"");if(!/^[-_a-zA-Z0-9#.:* ,>+~[\]()=^$|]+$/.test(c))throw Error("Selector allows only [-_a-zA-Z0-9#.:* ,>+~[\\]()=^$|] and strings, got: "+a);a:{for(var d={"(":")","[":"]"},f=[],g=0;g<c.length;g++){var k=c[g];if(d[k])f.push(d[k]);else if(Jb(d,k)&&f.pop()!=k){c=!1;break a}}c=0==f.length}if(!c)throw Error("() and [] in selector must be balanced, got: "+a);
if(!(b instanceof J)){c="";for(var l in b){if(!/^[-_a-zA-Z0-9]+$/.test(l))throw Error("Name allows only [-_a-zA-Z0-9], got: "+l);d=b[l];null!=d&&(d=x(d)?jb(d,sc).join(" "):sc(d),c+=l+":"+d+";")}b=c?(new J).Ta(c):nc}b instanceof J&&b.constructor===J&&b.vf===mc?l=b.Lc:(Wa(b),l="type_error:SafeStyle");return(new uc).Ta(a+"{"+l+"}")},xc=function(a){var b="",c=function(a){x(a)?hb(a,c):b+=wc(a)};hb(arguments,c);return(new uc).Ta(b)};uc.prototype.ca=function(){return this.Kc};
var wc=function(a){if(a instanceof uc&&a.constructor===uc&&a.uf===tc)return a.Kc;Wa(a);return"type_error:SafeStyleSheet"};uc.prototype.Ta=function(a){this.Kc=a;return this};var yc=function(a,b){this.width=a;this.height=b};yc.prototype.clone=function(){return new yc(this.width,this.height)};yc.prototype.Sf=function(){return this.width*this.height};yc.prototype.isEmpty=function(){return!this.Sf()};yc.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var Ac=function(a){return a?new zc(9==a.nodeType?a:a.ownerDocument||a.document):eb||(eb=new zc)},K=function(a){return v(a)?document.getElementById(a):a},Cc=function(a,b){Gb(b,function(b,d){b&&typeof b==p&&b.ma&&(b=b.ca());"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Bc.hasOwnProperty(d)?a.setAttribute(Bc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},Bc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",
frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Ec=function(a,b,c){return Dc(document,arguments)},Dc=function(a,b){var c=String(b[0]),d=b[1];if(!bc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',Cb(d.name),'"');if(d.type){c.push(' type="',Cb(d.type),'"');var f={};Mb(f,d);delete f.type;d=f}c.push(">");c=c.join("")}c=a.createElement(c);d&&(v(d)?c.className=d:x(d)?c.className=
d.join(" "):Cc(c,d));2<b.length&&Fc(a,c,b,2);return c},Fc=function(a,b,c,d){function f(c){c&&b.appendChild(v(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var g=c[d];!Xa(g)||Za(g)&&0<g.nodeType?f(g):hb(Gc(g)?pb(g):g,f)}},Hc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},Gc=function(a){if(a&&typeof a.length==ya){if(Za(a))return typeof a.item==m||"string"==typeof a.item;if(Ya(a))return typeof a.item==m}return!1},zc=function(a){this.ja=a||t.document||document};r=zc.prototype;
r.Ma=function(a){return v(a)?this.ja.getElementById(a):a};r.getElementsByTagName=function(a,b){return(b||this.ja).getElementsByTagName(String(a))};
r.Kd=function(a,b,c){c=c||this.ja;a=a&&"*"!=a?String(a).toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))b=c.querySelectorAll(a+(b?"."+b:""));else if(b&&c.getElementsByClassName)if(c=c.getElementsByClassName(b),a){for(var d={},f=0,g=0,k;k=c[g];g++)a==k.nodeName&&(d[f++]=k);d.length=f;b=d}else b=c;else if(c=c.getElementsByTagName(a||"*"),b){d={};for(g=f=0;k=c[g];g++)a=k.className,typeof a.split==m&&A(a.split(/\s+/),b)&&(d[f++]=k);d.length=f;b=d}else b=c;return b};
r.hc=function(a,b,c){return Dc(this.ja,arguments)};r.createElement=function(a){return this.ja.createElement(String(a))};r.createTextNode=function(a){return this.ja.createTextNode(String(a))};r.appendChild=function(a,b){a.appendChild(b)};r.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var L=function(){this.ta=this.ta;this.Jb=this.Jb};L.prototype.ta=!1;L.prototype.ia=function(){this.ta||(this.ta=!0,this.h())};L.prototype.h=function(){if(this.Jb)for(;this.Jb.length;)this.Jb.shift()()};var Ic=function(a){a&&typeof a.ia==m&&a.ia()};var Jc=!D||9<=Number($b),Kc=D&&!Zb("9"),Lc=function(){if(!t.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});t.addEventListener("test",Ua,b);t.removeEventListener("test",Ua,b);return a}();var M=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.qa=!1;this.De=!0};M.prototype.stopPropagation=function(){this.qa=!0};M.prototype.preventDefault=function(){this.defaultPrevented=!0;this.De=!1};var N=function(a,b){M.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.va=null;a&&this.Wd(a,b)};z(N,M);
N.prototype.Wd=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(E){a:{try{Ob(b.nodeName);var d=!0;break a}catch(f){}d=!1}d||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||(c==ta?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.va=a;a.defaultPrevented&&
this.preventDefault()};N.prototype.stopPropagation=function(){N.l.stopPropagation.call(this);this.va.stopPropagation?this.va.stopPropagation():this.va.cancelBubble=!0};N.prototype.preventDefault=function(){N.l.preventDefault.call(this);var a=this.va;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Kc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Mc="closure_listenable_"+(1E6*Math.random()|0),Nc=function(a){return!(!a||!a[Mc])},Oc=0;var Pc=function(a,b,c,d,f,g){this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!f;this.wb=g;this.key=++Oc;this.Da=this.lb=!1};Pc.prototype.Hb=function(){this.Da=!0;this.wb=this.src=this.proxy=this.listener=null};var Qc=function(a){this.src=a;this.m={};this.fb=0};r=Qc.prototype;r.add=function(a,b,c,d,f){var g=a.toString();a=this.m[g];a||(a=this.m[g]=[],this.fb++);var k=Rc(a,b,d,f);-1<k?(b=a[k],c||(b.lb=!1)):(b=new Pc(b,null,this.src,g,!!d,f),b.lb=c,a.push(b));return b};r.remove=function(a,b,c,d){a=a.toString();if(!(a in this.m))return!1;var f=this.m[a];b=Rc(f,b,c,d);return-1<b?(f[b].Hb(),Array.prototype.splice.call(f,b,1),0==f.length&&(delete this.m[a],this.fb--),!0):!1};
r.ye=function(a){var b=a.type;if(!(b in this.m))return!1;var c=nb(this.m[b],a);c&&(a.Hb(),0==this.m[b].length&&(delete this.m[b],this.fb--));return c};r.Lb=function(a){a=a&&a.toString();var b=0,c;for(c in this.m)if(!a||c==a){for(var d=this.m[c],f=0;f<d.length;f++)++b,d[f].Hb();delete this.m[c];this.fb--}return b};r.Na=function(a,b,c,d){a=this.m[a.toString()];var f=-1;a&&(f=Rc(a,b,c,d));return-1<f?a[f]:null};
var Rc=function(a,b,c,d){for(var f=0;f<a.length;++f){var g=a[f];if(!g.Da&&g.listener==b&&g.capture==!!c&&g.wb==d)return f}return-1};var Sc="closure_lm_"+(1E6*Math.random()|0),Tc={},Uc=0,O=function(a,b,c,d,f){if(d&&d.once)return Vc(a,b,c,d,f);if(x(b)){for(var g=0;g<b.length;g++)O(a,b[g],c,d,f);return null}c=Wc(c);return Nc(a)?a.Ca(b,c,Za(d)?!!d.capture:!!d,f):Xc(a,b,c,!1,d,f)},Xc=function(a,b,c,d,f,g){if(!b)throw Error("Invalid event type");var k=Za(f)?!!f.capture:!!f,l=Yc(a);l||(a[Sc]=l=new Qc(a));c=l.add(b,c,d,k,g);if(c.proxy)return c;d=Zc();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)Lc||(f=k),void 0===f&&(f=!1),a.addEventListener(b.toString(),
d,f);else if(a.attachEvent)a.attachEvent($c(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Uc++;return c},Zc=function(){var a=ad,b=Jc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},Vc=function(a,b,c,d,f){if(x(b)){for(var g=0;g<b.length;g++)Vc(a,b[g],c,d,f);return null}c=Wc(c);return Nc(a)?a.zc(b,c,Za(d)?!!d.capture:!!d,f):Xc(a,b,c,!0,d,
f)},bd=function(a,b,c,d,f){if(x(b)){for(var g=0;g<b.length;g++)bd(a,b[g],c,d,f);return null}d=Za(d)?!!d.capture:!!d;c=Wc(c);if(Nc(a))return a.Rb(b,c,d,f);if(!a)return!1;if(a=Yc(a))if(b=a.Na(b,c,d,f))return P(b);return!1},P=function(a){if(typeof a==ya||!a||a.Da)return!1;var b=a.src;if(Nc(b))return b.Ue(a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent($c(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Uc--;(c=Yc(b))?(c.ye(a),
0==c.fb&&(c.src=null,b[Sc]=null)):a.Hb();return!0},cd=function(a,b){if(!a)return 0;if(Nc(a))return a.xe(b);a=Yc(a);if(!a)return 0;var c=0;b=b&&b.toString();for(var d in a.m)if(!b||d==b)for(var f=a.m[d].concat(),g=0;g<f.length;++g)P(f[g])&&++c;return c},$c=function(a){return a in Tc?Tc[a]:Tc[a]="on"+a},ed=function(a,b,c,d){var f=!0;if(a=Yc(a))if(b=a.m[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.Da&&(g=dd(g,d),f=f&&!1!==g)}return f},dd=function(a,b){var c=a.listener,
d=a.wb||a.src;a.lb&&P(a);return c.call(d,b)},ad=function(a,b){if(a.Da)return!0;if(!Jc){if(!b)a:{b=["window","event"];for(var c=t,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new N(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var f=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(k){f=!0}if(f||void 0==d.returnValue)d.returnValue=!0}d=[];for(f=b.currentTarget;f;f=f.parentNode)d.push(f);a=a.type;for(f=d.length-1;!b.qa&&0<=f;f--){b.currentTarget=d[f];var g=ed(d[f],a,
!0,b);c=c&&g}for(f=0;!b.qa&&f<d.length;f++)b.currentTarget=d[f],g=ed(d[f],a,!1,b),c=c&&g}return c}return dd(a,new N(b,this))},Yc=function(a){a=a[Sc];return a instanceof Qc?a:null},fd="__closure_events_fn_"+(1E9*Math.random()>>>0),Wc=function(a){if(Ya(a))return a;a[fd]||(a[fd]=function(b){return a.handleEvent(b)});return a[fd]};var Q=function(){L.call(this);this.ba=new Qc(this);this.Mf=this;this.Gc=null};z(Q,L);Q.prototype[Mc]=!0;r=Q.prototype;r.addEventListener=function(a,b,c,d){O(this,a,b,c,d)};r.removeEventListener=function(a,b,c,d){bd(this,a,b,c,d)};
r.dispatchEvent=function(a){var b=this.Gc;if(b){var c=[];for(var d=1;b;b=b.Gc)c.push(b),++d}b=this.Mf;d=a.type||a;if(v(a))a=new M(a,b);else if(a instanceof M)a.target=a.target||b;else{var f=a;a=new M(d,b);Mb(a,f)}f=!0;if(c)for(var g=c.length-1;!a.qa&&0<=g;g--){var k=a.currentTarget=c[g];f=k.sb(d,!0,a)&&f}a.qa||(k=a.currentTarget=b,f=k.sb(d,!0,a)&&f,a.qa||(f=k.sb(d,!1,a)&&f));if(c)for(g=0;!a.qa&&g<c.length;g++)k=a.currentTarget=c[g],f=k.sb(d,!1,a)&&f;return f};
r.h=function(){Q.l.h.call(this);this.xe();this.Gc=null};r.Ca=function(a,b,c,d){return this.ba.add(String(a),b,!1,c,d)};r.zc=function(a,b,c,d){return this.ba.add(String(a),b,!0,c,d)};r.Rb=function(a,b,c,d){return this.ba.remove(String(a),b,c,d)};r.Ue=function(a){return this.ba.ye(a)};r.xe=function(a){return this.ba?this.ba.Lb(a):0};
r.sb=function(a,b,c){a=this.ba.m[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,f=0;f<a.length;++f){var g=a[f];if(g&&!g.Da&&g.capture==b){var k=g.listener,l=g.wb||g.src;g.lb&&this.Ue(g);d=!1!==k.call(l,c)&&d}}return d&&0!=c.De};r.Na=function(a,b,c,d){return this.ba.Na(String(a),b,c,d)};var gd="StopIteration"in t?t.StopIteration:{message:"StopIteration",stack:""},hd=function(){};hd.prototype.next=function(){throw gd;};hd.prototype.ac=function(){return this};var id=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},jd=function(a){a=String(a);if(id(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};var kd=function(){};kd.prototype.wd=null;kd.prototype.Pd=function(){return this.wd||(this.wd=this.Ig())};var ld,md=function(){};z(md,kd);md.prototype.Ad=function(){var a=this.Qd();return a?new ActiveXObject(a):new XMLHttpRequest};md.prototype.Ig=function(){var a={};this.Qd()&&(a[0]=!0,a[1]=!0);return a};
md.prototype.Qd=function(){if(!this.Ud&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var a=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],b=0;b<a.length;b++){var c=a[b];try{return new ActiveXObject(c),this.Ud=c}catch(d){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return this.Ud};ld=new md;var nd=function(a,b){this.j={};this.c=[];this.gb=this.b=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};r=nd.prototype;r.o=function(){return this.b};r.v=function(){this.ob();for(var a=[],b=0;b<this.c.length;b++)a.push(this.j[this.c[b]]);return a};r.K=function(){this.ob();return this.c.concat()};r.ha=function(a){return od(this.j,a)};r.isEmpty=function(){return 0==this.b};
r.clear=function(){this.j={};this.gb=this.b=this.c.length=0};r.remove=function(a){return od(this.j,a)?(delete this.j[a],this.b--,this.gb++,this.c.length>2*this.b&&this.ob(),!0):!1};r.ob=function(){if(this.b!=this.c.length){for(var a=0,b=0;a<this.c.length;){var c=this.c[a];od(this.j,c)&&(this.c[b++]=c);a++}this.c.length=b}if(this.b!=this.c.length){var d={};for(b=a=0;a<this.c.length;)c=this.c[a],od(d,c)||(this.c[b++]=c,d[c]=1),a++;this.c.length=b}};
r.get=function(a,b){return od(this.j,a)?this.j[a]:b};r.set=function(a,b){od(this.j,a)||(this.b++,this.c.push(a),this.gb++);this.j[a]=b};r.addAll=function(a){if(a instanceof nd)for(var b=a.K(),c=0;c<b.length;c++)this.set(b[c],a.get(b[c]));else for(b in a)this.set(b,a[b])};r.forEach=function(a,b){for(var c=this.K(),d=0;d<c.length;d++){var f=c[d],g=this.get(f);a.call(b,g,f,this)}};r.clone=function(){return new nd(this)};
r.ac=function(a){this.ob();var b=0,c=this.gb,d=this,f=new hd;f.next=function(){if(c!=d.gb)throw Error("The map has changed since the iterator was created");if(b>=d.c.length)throw gd;var f=d.c[b++];return a?f:d.j[f]};return f};var od=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var pd=function(a){if(a.v&&typeof a.v==m)return a.v();if(v(a))return a.split("");if(Xa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Hb(a)},qd=function(a,b,c){if(a.forEach&&typeof a.forEach==m)a.forEach(b,c);else if(Xa(a)||v(a))hb(a,b,c);else{if(a.K&&typeof a.K==m)var d=a.K();else if(a.v&&typeof a.v==m)d=void 0;else if(Xa(a)||v(a)){d=[];for(var f=a.length,g=0;g<f;g++)d.push(g)}else d=Ib(a);f=pd(a);g=f.length;for(var k=0;k<g;k++)b.call(c,f[k],d&&d[k],a)}};var rd=function(a,b,c){if(Ya(a))c&&(a=y(a,c));else if(a&&typeof a.handleEvent==m)a=y(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:t.setTimeout(a,b||0)};var sd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,td=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),f=null;if(0<=d){var g=a[c].substring(0,d);f=a[c].substring(d+1)}else g=a[c];b(g,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};var R=function(a){Q.call(this);this.headers=new nd;this.Wb=a||null;this.X=!1;this.Vb=this.a=null;this.yc="";this.Ba=0;this.na=this.tc=this.zb=this.mc=!1;this.ra=0;this.Qb=null;this.Ea="";this.Wc=this.vh=this.W=!1};z(R,Q);var ud=/^https?$/i,vd=["POST","PUT"],wd=[],xd=function(a,b,c,d,f,g,k){var l=new R;wd.push(l);b&&l.Ca(e,b);l.zc(Aa,l.Wf);g&&l.Rc(g);k&&l.Sc(k);l.send(a,c,d,f);return l};r=R.prototype;r.Wf=function(){this.ia();nb(wd,this)};r.Rc=function(a){this.ra=Math.max(0,a)};
r.Eh=function(a){this.Ea=a};r.Sc=function(a){this.W=a};
r.send=function(a,b,c,d){if(this.a)throw Error("[goog.net.XhrIo] Object is active with another request="+this.yc+"; newUri="+a);b=b?b.toUpperCase():"GET";this.yc=a;this.Ba=0;this.mc=!1;this.X=!0;this.a=this.Zf();this.Vb=this.Wb?this.Wb.Pd():ld.Pd();this.a.onreadystatechange=y(this.se,this);this.vh&&"onprogress"in this.a&&(this.a.onprogress=y(function(a){this.qe(a,!0)},this),this.a.upload&&(this.a.upload.onprogress=y(this.qe,this)));try{this.tc=!0,this.a.open(b,String(a),!0),this.tc=!1}catch(g){this.Id(5,
g);return}a=c||"";var f=this.headers.clone();d&&qd(d,function(a,b){f.set(b,a)});d=lb(f.K(),yd);c=t.FormData&&a instanceof t.FormData;!A(vd,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.Ea&&(this.a.responseType=this.Ea);"withCredentials"in this.a&&this.a.withCredentials!==this.W&&(this.a.withCredentials=this.W);try{this.xd(),0<this.ra&&((this.Wc=zd(this.a))?(this.a.timeout=this.ra,this.a.ontimeout=
y(this.Se,this)):this.Qb=rd(this.Se,this.ra,this)),this.zb=!0,this.a.send(a),this.zb=!1}catch(g){this.Id(5,g)}};var zd=function(a){return D&&Zb(9)&&typeof a.timeout==ya&&u(a.ontimeout)},yd=function(a){return"content-type"==a.toLowerCase()};r=R.prototype;r.Zf=function(){return this.Wb?this.Wb.Ad():ld.Ad()};r.Se=function(){"undefined"!=typeof Ra&&this.a&&(this.Ba=8,this.dispatchEvent("timeout"),this.abort(8))};
r.Id=function(a){this.X=!1;this.a&&(this.na=!0,this.a.abort(),this.na=!1);this.Ba=a;this.Fd();this.nb()};r.Fd=function(){this.mc||(this.mc=!0,this.dispatchEvent(e),this.dispatchEvent("error"))};r.abort=function(a){this.a&&this.X&&(this.X=!1,this.na=!0,this.a.abort(),this.na=!1,this.Ba=a||7,this.dispatchEvent(e),this.dispatchEvent("abort"),this.nb())};r.h=function(){this.a&&(this.X&&(this.X=!1,this.na=!0,this.a.abort(),this.na=!1),this.nb(!0));R.l.h.call(this)};
r.se=function(){this.ta||(this.tc||this.zb||this.na?this.re():this.ph())};r.ph=function(){this.re()};r.re=function(){if(this.X&&"undefined"!=typeof Ra&&(!this.Vb[1]||4!=this.ub()||2!=this.getStatus()))if(this.zb&&4==this.ub())rd(this.se,0,this);else if(this.dispatchEvent("readystatechange"),this.Lg()){this.X=!1;try{this.Xa()?(this.dispatchEvent(e),this.dispatchEvent(Ia)):(this.Ba=6,this.Fd())}finally{this.nb()}}};
r.qe=function(a,b){this.dispatchEvent(Ad(a,"progress"));this.dispatchEvent(Ad(a,b?"downloadprogress":"uploadprogress"))};var Ad=function(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}};r=R.prototype;r.nb=function(a){if(this.a){this.xd();var b=this.a,c=this.Vb[0]?Ua:null;this.Vb=this.a=null;a||this.dispatchEvent(Aa);try{b.onreadystatechange=c}catch(d){}}};r.xd=function(){this.a&&this.Wc&&(this.a.ontimeout=null);this.Qb&&(t.clearTimeout(this.Qb),this.Qb=null)};
r.Bb=function(){return!!this.a};r.Lg=function(){return 4==this.ub()};r.Xa=function(){var a=this.getStatus();a:switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var b=!0;break a;default:b=!1}return b||0===a&&!this.Mg()};r.Mg=function(){var a=String(this.yc).match(sd)[1]||null;!a&&t.self&&t.self.location&&(a=t.self.location.protocol,a=a.substr(0,a.length-1));return ud.test(a?a.toLowerCase():"")};r.ub=function(){return this.a?this.a.readyState:0};
r.getStatus=function(){try{return 2<this.ub()?this.a.status:-1}catch(a){return-1}};r.qg=function(){try{return this.a?this.a.responseText:""}catch(a){return""}};r.Rd=function(a){if(this.a){var b=this.a.responseText;a&&0==b.indexOf(a)&&(b=b.substring(a.length));a:{a=b;if(t.JSON)try{var c=t.JSON.parse(a);break a}catch(d){}c=jd(a)}return c}};
r.pg=function(){try{if(!this.a)return null;if("response"in this.a)return this.a.response;switch(this.Ea){case "":case "text":return this.a.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in this.a)return this.a.mozResponseArrayBuffer}return null}catch(a){return null}};var Bd=function(){};Bd.prototype.V=function(){return"NONE"};Bd.prototype.pa=function(){return null};Bd.prototype.Zd=function(){return!1};var Cd=function(a){this.label=a};z(Cd,Bd);Cd.prototype.R=function(){return this.label};var S=function(a,b,c){this.label=b;this.value=a.V();this.Kg=c;this.nc=a};z(S,Bd);r=S.prototype;r.R=function(){return this.label};r.V=function(){return this.value};r.Zd=function(){return this.Kg};r.encode=function(){return this.nc.encode()+"="};r.pa=function(){return new Dd(this)};var Ed=function(){};z(Ed,Bd);Ed.prototype.encode=function(){return encodeURIComponent(this.V())};Ed.prototype.pa=function(){return null};var Fd=function(a){S.call(this,a,a.R(),!0)};z(Fd,S);var Gd=function(){};z(Gd,Ed);Gd.prototype.R=function(){return"\u1ea8n danh"};Gd.prototype.V=function(){return"ANON"};Gd.prototype.decode=function(){return new Fd(this)};var Hd=function(a,b){this.pb=this.Xc=this.Fa="";this.Kb=null;this.La=this.ue="";this.F=this.Ng=!1;var c;a instanceof Hd?(this.F=u(b)?b:a.F,this.Ne(a.Fa),this.Qe(a.Xc),this.He(a.pb),this.Le(a.Kb),this.setPath(a.getPath()),this.Me(a.ea.clone()),this.Je(a.La)):a&&(c=String(a).match(sd))?(this.F=!!b,this.Ne(c[1]||"",!0),this.Qe(c[2]||"",!0),this.He(c[3]||"",!0),this.Le(c[4]),this.setPath(c[5]||"",!0),this.Me(c[6]||"",!0),this.Je(c[7]||"",!0)):(this.F=!!b,this.ea=new Id(null,null,this.F))};r=Hd.prototype;
r.toString=function(){var a=[],b=this.Fa;b&&a.push(Jd(b,Kd,!0),":");var c=this.pb;if(c||"file"==b)a.push("//"),(b=this.Xc)&&a.push(Jd(b,Kd,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.Kb,null!=c&&a.push(":",String(c));if(c=this.getPath())this.Bg()&&"/"!=c.charAt(0)&&a.push("/"),a.push(Jd(c,"/"==c.charAt(0)?Ld:Md,!0));(c=this.jg())&&a.push("?",c);(c=this.La)&&a.push("#",Jd(c,Nd));return a.join("")};r.clone=function(){return new Hd(this)};
r.Ne=function(a,b){this.aa();if(this.Fa=b?Od(a,!0):a)this.Fa=this.Fa.replace(/:$/,"");return this};r.Qe=function(a,b){this.aa();this.Xc=b?Od(a):a;return this};r.He=function(a,b){this.aa();this.pb=b?Od(a,!0):a;return this};r.Bg=function(){return!!this.pb};r.Le=function(a){this.aa();if(a){a=Number(a);if(isNaN(a)||0>a)throw Error("Bad port number "+a);this.Kb=a}else this.Kb=null;return this};r.getPath=function(){return this.ue};r.setPath=function(a,b){this.aa();this.ue=b?Od(a,!0):a;return this};
r.Me=function(a,b){this.aa();a instanceof Id?(this.ea=a,this.ea.Qc(this.F)):(b||(a=Jd(a,Pd)),this.ea=new Id(a,null,this.F));return this};r.jg=function(){return this.ea.toString()};r.Ob=function(a,b){this.aa();this.ea.set(a,b);return this};r.Je=function(a,b){this.aa();this.La=b?Od(a):a;return this};r.aa=function(){if(this.Ng)throw Error("Tried to modify a read-only Uri");};r.Qc=function(a){this.F=a;this.ea&&this.ea.Qc(a);return this};
var Od=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Jd=function(a,b,c){return v(a)?(a=encodeURI(a).replace(b,Qd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Qd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Kd=/[#\/\?@]/g,Md=/[#\?:]/g,Ld=/[#\?]/g,Pd=/[#\?@]/g,Nd=/#/g,Id=function(a,b,c){this.b=this.g=null;this.Z=a||null;this.F=!!c};r=Id.prototype;
r.O=function(){if(!this.g&&(this.g=new nd,this.b=0,this.Z)){var a=this;td(this.Z,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)})}};r.o=function(){this.O();return this.b};r.add=function(a,b){this.O();this.Aa();a=this.xa(a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.b+=1;return this};r.remove=function(a){this.O();a=this.xa(a);return this.g.ha(a)?(this.Aa(),this.b-=this.g.get(a).length,this.g.remove(a)):!1};r.clear=function(){this.Aa();this.g=null;this.b=0};
r.isEmpty=function(){this.O();return 0==this.b};r.ha=function(a){this.O();a=this.xa(a);return this.g.ha(a)};r.forEach=function(a,b){this.O();this.g.forEach(function(c,d){hb(c,function(c){a.call(b,c,d,this)},this)},this)};r.K=function(){this.O();for(var a=this.g.v(),b=this.g.K(),c=[],d=0;d<b.length;d++)for(var f=a[d],g=0;g<f.length;g++)c.push(b[d]);return c};r.v=function(a){this.O();var b=[];if(v(a))this.ha(a)&&(b=ob(b,this.g.get(this.xa(a))));else{a=this.g.v();for(var c=0;c<a.length;c++)b=ob(b,a[c])}return b};
r.set=function(a,b){this.O();this.Aa();a=this.xa(a);this.ha(a)&&(this.b-=this.g.get(a).length);this.g.set(a,[b]);this.b+=1;return this};r.get=function(a,b){if(!a)return b;a=this.v(a);return 0<a.length?String(a[0]):b};r.setValues=function(a,b){this.remove(a);0<b.length&&(this.Aa(),this.g.set(this.xa(a),pb(b)),this.b+=b.length)};
r.toString=function(){if(this.Z)return this.Z;if(!this.g)return"";for(var a=[],b=this.g.K(),c=0;c<b.length;c++){var d=b[c],f=encodeURIComponent(String(d));d=this.v(d);for(var g=0;g<d.length;g++){var k=f;""!==d[g]&&(k+="="+encodeURIComponent(String(d[g])));a.push(k)}}return this.Z=a.join("&")};r.Aa=function(){this.Z=null};r.clone=function(){var a=new Id;a.Z=this.Z;this.g&&(a.g=this.g.clone(),a.b=this.b);return a};r.xa=function(a){a=String(a);this.F&&(a=a.toLowerCase());return a};
r.Qc=function(a){a&&!this.F&&(this.O(),this.Aa(),this.g.forEach(function(a,c){var b=c.toLowerCase();c!=b&&(this.remove(c),this.setValues(b,a))},this));this.F=a};var Rd="";var Sd=function(){"loading"!=document.readyState?this.Xd():O(window,"load",this.Xd)};Sd.prototype.Xd=function(){var a=Array.prototype.slice.call(document.getElementsByTagName("link"),0);Pa();var b=a[Symbol.iterator];a=b?b.call(a):Oa(a);for(b=a.next();!b.done;b=a.next())b=b.value,b.getAttribute("data-async-css")==Ja&&b.getAttribute("media")==n&&b.setAttribute("media","all")};var Td=function(a){if(a.classList)return a.classList;a=a.className;return v(a)&&a.match(/\S+/g)||[]},Ud=function(a,b){return a.classList?a.classList.contains(b):A(Td(a),b)},Vd=function(a,b){a.classList?a.classList.add(b):Ud(a,b)||(a.className+=0<a.className.length?" "+b:b)},Wd=function(a,b){a.classList?a.classList.remove(b):Ud(a,b)&&(a.className=ib(Td(a),function(a){return a!=b}).join(" "))};var Xd=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=F&&!b&&!c;if((!u(b)||d)&&a.getBoundingClientRect){a:{try{var f=a.getBoundingClientRect()}catch(g){f={left:0,top:0,right:0,bottom:0};break a}D&&a.ownerDocument.body&&(a=a.ownerDocument,f.left-=a.documentElement.clientLeft+a.body.clientLeft,f.top-=a.documentElement.clientTop+a.body.clientTop)}return new yc(f.right-f.left,f.bottom-f.top)}return new yc(b,c)},Yd=function(a,b){a.style.display=b?"":n},$d=function(a,b){b=Ac(b);var c=b.ja;if(D&&c.createStyleSheet)return b=
c.createStyleSheet(),Zd(b,a),b;c=b.Kd("HEAD")[0];if(!c){var d=b.Kd("BODY")[0];c=b.hc("HEAD");d.parentNode.insertBefore(c,d)}d=b.hc("STYLE");Zd(d,a);b.appendChild(c,d);return d},Zd=function(a,b){b=wc(b);D&&u(a.cssText)?a.cssText=b:a.innerHTML=b};/*

 CC0 1.0 Universal License
 Public Domain Dedication

 The person(s) who associated a work with this deed has dedicated the work to
 the public domain by waiving all of his or her rights to the work worldwide
 under copyright law, including all related and neighboring rights, to the
 extent allowed by law.

 You can copy, modify, distribute and perform the work, even for commercial
 purposes, all without asking permission.

 In no way are the patent or trademark rights of any person affected by CC0,
 nor are the rights that other persons may have in the work or in how the work
 is used, such as publicity or privacy rights.

 Unless expressly stated otherwise, the person(s) who associated a work with
 this deed makes no warranties about the work, and disclaims liability for all
 uses of the work, to the fullest extent permitted by applicable law.

 When using or citing the work, you should not imply endorsement by the author
 or the affirmer.

 This is a human-readable summary of the Legal Code (read the full text).
 svg4everybody v2.1.8 | github.com/jonathantneal/svg4everybody */
function ae(a,b,c){if(c){var d=document.createDocumentFragment(),f=!b.hasAttribute("viewBox")&&c.getAttribute("viewBox");f&&b.setAttribute("viewBox",f);for(b=c.cloneNode(!0);b.childNodes.length;)d.appendChild(b.firstChild);a.appendChild(d)}}
function be(a){a.onreadystatechange=function(){if(4===a.readyState){var b=a.Lf;b||(b=a.Lf=document.implementation.createHTMLDocument(""),b.body.innerHTML=a.responseText,a.kd={});a.ld.splice(0).map(function(c){var d=a.kd[c.id];d||(d=a.kd[c.id]=b.getElementById(c.id));ae(c.parent,c.Hh,d)})}};a.onreadystatechange()}function ce(){return"undefined"!=typeof LEGACY_SUPPORT&&LEGACY_SUPPORT}
var ge=function(a){function b(){for(var a=0;a<sb.length;){var g=sb[a],k=g.parentNode,l;for(l=k;"svg"!==l.nodeName.toLowerCase()&&(l=l.parentNode,l););if(l){var q=g.getAttribute("xlink:href")||g.getAttribute("href");!q&&c.attributeName&&(q=g.getAttribute(c.attributeName));if(ce()&&f){var I=document.createElement("img");I.style.cssText="display:inline-block;height:100%;width:100%";I.setAttribute("width",l.getAttribute("width")||l.clientWidth);I.setAttribute("height",l.getAttribute("height")||l.clientHeight);
I.src=d(q,l,g);k.replaceChild(I,g)}else de&&(!c.Jh||c.Jh(q,l,g)?(k.removeChild(g),q=q.split("#"),g=q.shift(),q=q.join("#"),g.length?(I=ee[g],I||(I=ee[g]=new XMLHttpRequest,I.open("GET",g),I.send(),I.ld=[]),I.ld.push({parent:k,Hh:l,id:q}),be(I)):ae(k,l,document.getElementById(q))):(++a,++fe))}else++a}if(!sb.length||0<sb.length-fe)window.requestAnimationFrame?window.requestAnimationFrame(b):setTimeout(b,67)}var c=Object(a);if(ce()){var d=c.Ph||function(a){return a.replace(/\?[^#]+/,"").replace("#",
".").replace(/^\./,"")+".png"+(/\?[^#]+/.exec(a)||[""])[0]};var f="nosvg"in c?c.Rh:/\bMSIE [1-8]\b/.test(navigator.userAgent)}a=/\bMSIE [1-8]\.0\b/;var g=/\bTrident\/[567]\b|\bMSIE (?:9|10)\.0\b/,k=/\bAppleWebKit\/(\d+)\b/,l=/\bEdge\/12\.(\d+)\b/,q=/\bEdge\/.(\d+)\b/,Z=window.top!==window.self;var de="polyfill"in c?c.Th:ce()?a.test(navigator.userAgent)||g.test(navigator.userAgent)||10547>(navigator.userAgent.match(l)||[])[1]||537>(navigator.userAgent.match(k)||[])[1]||q.test(navigator.userAgent)&&
Z:g.test(navigator.userAgent)||10547>(navigator.userAgent.match(l)||[])[1]||537>(navigator.userAgent.match(k)||[])[1]||q.test(navigator.userAgent)&&Z;var ee={},sb=document.getElementsByTagName("use"),fe=0;de&&b()};var he=function(a){return/^[A-Za-z0-9]+$/.test(a)||/^#[0-9A-Fa-f]{3}$/.test(a)||/^#[0-9A-Fa-f]{6}$/.test(a)||/^rgb *\( *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *\)$/.test(a)||/^rgba *\( *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *\)$/.test(a)},ie=function(a){a=a.split(",");for(var b=0;b<a.length;b++){var c=a[b];c=ub(c);if(!(/^[- A-Za-z0-9]*$/.test(c)||/^"[- A-Za-z0-9]*"$/.test(c)||/^'[- A-Za-z0-9]*'$/.test(c)))return!1}return!0},je=function(){if(window.parent&&window.parent.postMessage){var a=
document.getElementById("previewHolder"),b=0;if(a){b:{b=9==a.nodeType?a:a.ownerDocument||a.document;if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,null))){b=b.display||b.getPropertyValue("display")||"";break b}b=""}if((b||(a.currentStyle?a.currentStyle.display:null)||a.style&&a.style.display)!=n)a=Xd(a);else{b=a.style;var c=b.display,d=b.visibility,f=b.position;b.visibility=oa;b.position="absolute";b.display="inline";a=Xd(a);b.display=c;b.position=f;b.visibility=
d}b=a.height}a=document.getElementById(da);c=0;a&&(c=a.offsetHeight);b=(b=Math.max(b,c||document.body.offsetHeight))||230;a="amp=1"==(new Hd(document.location.href)).La?{sentinel:"amp",type:"embed-size",height:b}:"set-comment-editor-height "+b+"px";window.parent.postMessage(a,"*")}},ke=function(){var a=document.getElementById(ia),b=document.getElementById(za),c=document.getElementById("postCommentPreview"),d=function(){b&&(b.disabled=""==a.value);c&&(c.disabled=""==a.value)};a&&"oninput"in a&&(d(null),
O(a,sa,d))},le=function(a){var b=[];D&&b.push(vc(".previewMode .postCommentButtonHolder",{"padding-top":"22px"}));var c=(new Hd(a)).La;if(0!=c.length){a=null;try{c=decodeURIComponent(c),a=JSON.parse(c)}catch(k){}if(a&&a.color){c=tb(rb(a.color));var d=tb(rb(a.unvisitedLinkColor));a=tb(rb(a.fontFamily));he(c)&&he(d)&&ie(a)&&(b.push(vc("body",{color:c,"font-family":a})),b.push(vc("a:link, a:visited, a:active, a:hover",{color:d})))}}$d(xc(b));setTimeout(je,100);var f=K(da);if((b=K(ia))&&f){var g=!1;O(b,
"focus",function(){g||(g=!0,Wd(f,"compact"),je())})}ge();new Sd};var me=function(a){a=K(a);var b=a.nodeName.toLowerCase();a.style.display="span"==b||"img"==b||"a"==b||b==sa||"select"==b?"inline":"block"},T=function(a){K(a).style.display=n};var U=function(a,b,c){var d;c&&T(wa);switch(a){case 0:a=d="captcha-error";break;case 1:a=d="id-error";break;case 2:case 3:case 4:a="main-error";d="main-error-holder";break;case 5:a=d="nameUrlDialogErrorHolder";break;default:throw Error("internal error in show message");}c?(K(a).innerHTML=b,me(d),K(ia).className="commentBody-err"):(Hc(K(a)),T(d));je()},ne=function(a){U(3,null,!1);K("main-status").innerHTML=a;me(wa);je()};var oe=function(){};oe.prototype.Gh=function(){T(ra);K(ia).disabled=!0;K(za).disabled=!0};oe.prototype.Cg=function(){me(ra);K(ia).disabled=!1;K(za).disabled=!1};var Dd=function(a){this.la=a};z(Dd,oe);r=Dd.prototype;r.Wa=function(){return!1};r.Pb=function(){if(!this.Wa())throw Error("Trying to show a non-editable identity");this.Gh();me(qa)};r.ce=function(){return!0};r.Tc=function(){if(!this.Wa())throw Error("Trying to show edit button for a non-editable identity");me("editButton")};r.we=function(){};r.Pc=function(){};r.Pa=function(){T(qa);T("editButton");T("settingsButton");T("commentDash");T(Ha);this.Cg()};var pe=function(a){a=a.className;return v(a)&&a.match(/\S+/g)||[]},qe=function(a,b){for(var c=pe(a),d=qb(arguments,1),f=c.length+d.length,g=0;g<d.length;g++)A(c,d[g])||c.push(d[g]);a.className=c.join(" ");return c.length==f},se=function(a,b){var c=pe(a),d=qb(arguments,1),f=re(c,d);a.className=f.join(" ");return f.length==c.length-d.length},re=function(a,b){return ib(a,function(a){return!A(b,a)})};var ve=function(a){for(var b=[],c=te,d=a.elements,f,g=0;f=d[g];g++)if(f.form==a&&!f.disabled&&"FIELDSET"!=f.tagName){var k=f.name;switch(f.type.toLowerCase()){case "file":case "submit":case "reset":case "button":break;case Da:f=ue(f);if(null!=f)for(var l,q=0;l=f[q];q++)c(b,k,l);break;default:l=ue(f),null!=l&&c(b,k,l)}}d=a.getElementsByTagName("INPUT");for(g=0;f=d[g];g++)f.form==a&&"image"==f.type.toLowerCase()&&(k=f.name,c(b,k,f.value),c(b,k+".x","0"),c(b,k+".y","0"));return b.join("&")},te=function(a,
b,c){a.push(encodeURIComponent(b)+"="+encodeURIComponent(c))},ue=function(a){var b=a.type;switch(v(b)&&b.toLowerCase()){case "checkbox":case "radio":return a.checked?a.value:null;case "select-one":return b=a.selectedIndex,0<=b?a.options[b].value:null;case Da:b=[];for(var c,d=0;c=a.options[d];d++)c.selected&&b.push(c.value);return b.length?b:null;default:return null!=a.value?a.value:null}};var we=!1,xe=!1,ye=!1,ze=function(a,b){xe=a;ye=b;window.parent==window.top&&(a||b)?(a=K(Ha),b?qe(a,"checked"):se(a,"checked"),me(Ha),K("ajaxAction").value=b?"UnsubscribeByEmail":"SubscribeByEmail"):T(Ha)};var Be=function(a,b){S.call(this,new Ae,a,!1);this.ig=b};z(Be,S);Be.prototype.encode=function(){return this.nc.encode()+"="+this.label+"="+this.ig};Be.prototype.R=function(){return this.label+" (Google)"};Be.prototype.pa=function(){return new Ce(this)};var Ae=function(){};z(Ae,Ed);Ae.prototype.R=function(){return""};Ae.prototype.V=function(){return"CURRENT"};Ae.prototype.decode=function(a){return new Be(a[1],a[2])};Ae.prototype.pa=function(){throw Error("internal error");};
var Ce=function(a){this.la=a};z(Ce,Dd);Ce.prototype.Tc=function(){(xe||ye)&&me(Ha)};var De=function(a){S.call(this,a,a.R(),!1)};z(De,S);var Ee=function(){};z(Ee,Ed);Ee.prototype.R=function(){return"Ta\u0300i khoa\u0309n Google"};Ee.prototype.V=function(){return"GOOGLE"};Ee.prototype.decode=function(){return this.Od()};Ee.prototype.Od=function(){return new De(this)};var Fe=function(a,b,c){S.call(this,a,null,!0);this.name=b;this.url=c};z(Fe,S);Fe.prototype.R=function(){return this.name+" ("+this.url+")"};Fe.prototype.encode=function(){return this.nc.encode()+"="+encodeURIComponent(this.name)+"="+encodeURIComponent(this.url)};Fe.prototype.pa=function(){return new Ge(this)};var He=function(){};z(He,Ed);He.prototype.R=function(){return"T\u00ean/URL"};He.prototype.V=function(){return"NAMEURL"};He.prototype.pa=function(){return new Ge(new Fe(this,"",""))};
He.prototype.decode=function(a){return new Fe(this,a[1],a[2])};var Ge=function(a){this.la=a};z(Ge,Dd);r=Ge.prototype;r.Wa=function(){return!0};r.Pb=function(){Ge.l.Pb.call(this);me(xa)};r.Pa=function(){Ge.l.Pa.call(this);T(xa);U(5,null,!1);this.Ke("");this.Pe("")};r.we=function(){this.Ke(this.la.name);this.Pe(this.la.url)};r.Pc=function(){Ge.l.Pc.call(this);this.la.name=this.Nd();this.la.url=this.sg();this.Tc()};
r.ce=function(){return""==this.Nd()?(U(5,"Kh\u00f4ng \u0111\u01b0\u1ee3c \u0111\u1ec3 tr\u1ed1ng t\u00ean",!0),!1):!0};r.Nd=function(){return K("anonNameField").value};r.Ke=function(a){K("anonNameField").value=a};r.sg=function(){return K("anonUrlField").value};r.Pe=function(a){K("anonUrlField").value=a};var Ie=function(){this.ka=[];this.Za=[];this.Ia=[];this.Sa=[];this.i=this.B=null;this.G=[]};r=Ie.prototype;r.Ab=function(a,b,c,d){for(var f=0;f<this.G.length;f++)if(a==this.G[f])return d(a);d=a.encode();for(f=0;f<this.G.length;f++)if(this.G[f].encode()==d)return c(this.G[f]);return b(a)};r.Hg=function(a){return this.Ab(a,y(function(a){return this.G[this.G.length]=a},this),cc,cc)};r.Cb=function(a){function b(){return!1}return this.Ab(a,function(){return!0},b,b)};
r.Va=function(a){function b(){throw Error("item should have been unique");}this.Ab(a,Ua,b,b);return this.Hg(a)};r.cc=function(a){return this.Ab(a,y(function(a){this.G[this.G.length]=a;return this.ka[this.ka.length]=a},this),cc,cc)};r.ke=function(){for(var a=document.getElementById("identityControlsHolder"),b=Td(a),c=0;c<b.length;c++)b[c].slice(0,14)==pa&&Wd(a,b[c]);(b=this.Sa[K(ra).selectedIndex])&&Vd(a,pa+b.value)};r.od=function(a){this.B=this.cc(a);this.ab();this.Ha();this.kb(!1);return this.B};
r.pd=function(a){this.Va(a);this.Za[this.Za.length]=a};r.Pf=function(){var a=this.Va(new Ee);this.pd(a.Od())};r.Of=function(){var a=new He;this.Va(a);this.Ia[this.Ia.length]=a};r.Nf=function(){var a=this.Va(new Gd);a=this.Va(new Fd(a));this.Ia[this.Ia.length]=a};r.Ha=function(){var a=this.Sa[K(ra).selectedIndex];if(a.constructor==Cd)this.ab();else{U(1,null,!1);this.i=a.pa();null!=this.i&&this.i.we();this.ke();var b=K("anonymousWarning");b&&(Yd(b,a.Zd()),je())}};
r.kb=function(a){if(null!=this.i){var b=this.i.la;if(a&&this.i.Wa()&&this.Cb(b)||!this.i.ce())this.i.Pb();else return this.i.Pc(),this.i.Pa(),this.i.Wa()&&this.i.Tc(),this.i=null,b}return null};r.yh=function(){this.$f(K("encodedIds").value);this.B=this.Cd(K(la).value);null==this.B&&0<this.ka.length&&(this.B=this.ka[0]);null==this.B&&1==this.Za.length&&(this.B=this.Za[0]);this.ab();null!=this.B&&(this.Ha(),this.kb(!1))};
r.qd=function(a,b){this.Sa[this.Sa.length]=b;var c=document.createElement("option");c.text=b.R();c.value=b.V();try{a.add(c,null)}catch(d){a.add(c)}this.B==b&&(c.selected=!0);return c};r.dc=function(a,b){for(var c=0;c<b.length;c++)this.qd(a,b[c])};r.ab=function(){for(var a=K(ra);0!=a.options.length;)a.remove(0);this.Sa=[];this.qd(a,new Cd("Ch\u1ecdn h\u1ed3 s\u01a1...")).disabled="disabled";this.dc(a,this.ka);this.dc(a,this.Za);this.dc(a,this.Ia)};
r.fg=function(){for(var a=[],b=0;b<this.ka.length;b++)a[a.length]=this.ka[b].encode();return a.join("&")};r.$f=function(a){if(""!=a){a=a.split("&");for(var b=0;b<a.length;b++)this.Cd(a[b])}};r.Cd=function(a){if(""==a)return null;a=a.split("=");for(var b=0;b<a.length;b++)a[b]=decodeURIComponent(a[b]);b=this.hg(a[0]);return null!=b?(a=b.decode(a),this.cc(a)):null};r.hg=function(a){for(var b=0;b<this.G.length;b++)if(this.G[b].encode()==a)return this.G[b];return null};
r.Xe=function(){var a=K(ia).value;if(""==a)return U(2,"Kh\u00f4ng \u0111\u01b0\u1ee3c \u0111\u1ec3 tr\u1ed1ng nh\u1eadn x\u00e9t",!0),!1;if(1E6<a.length)return U(2,"\u0110\u00f4\u0323 da\u0300i n\u00f4\u0323i dung v\u01b0\u01a1\u0323t qua\u0301 1MB. Ha\u0303y ru\u0301t ng\u0103\u0301n la\u0323i.",!0),!1;U(2,null,!1);return!0};r.Ec=function(){null!=this.i&&this.i.Pa();this.Ha();var a=this.kb(!0);null!=a&&(this.B=a)};r.fh=function(){var a=this.kb(!1);null!=a&&this.od(a)};
r.eh=function(){null!=this.i&&(this.i.Pa(),this.i=null);this.ab();this.Ec()};r.te=function(){if(null==this.B||"NONE"==this.B.V())return U(1,"H\u00e3y ch\u1ecdn h\u1ed3 s\u01a1",!0),!1;if(null!=this.i)return!1;K("encodedIds").value=this.fg();K(la).value=this.B.encode();return!0};r.hh=function(){this.B&&(this.Ha(),this.i.Pb())};r.nh=function(){this.Xe()&&this.te()&&this.Gd(!1)};r.oh=function(){this.Xe()&&this.te()&&this.Gd(!0)};
r.Gd=function(a){K(Ea).value=a?Ja:"false";this.Ha();a=K("commentForm");a.onsubmit();a.submit()};var Je=function(){se(K(da),"previewMode");return!0};var Ke;Nb("A AREA BUTTON HEAD INPUT LINK MENU META OPTGROUP OPTION PROGRESS STYLE SELECT SOURCE TEXTAREA TITLE TRACK".split(" "));var Le=function(a,b,c){L.call(this);this.Ac=a;this.Jg=b||0;this.ya=c;this.Tf=y(this.cg,this)};z(Le,L);r=Le.prototype;r.Qa=0;r.h=function(){Le.l.h.call(this);this.stop();delete this.Ac;delete this.ya};r.start=function(a){this.stop();this.Qa=rd(this.Tf,u(a)?a:this.Jg)};r.stop=function(){this.Bb()&&t.clearTimeout(this.Qa);this.Qa=0};r.Bb=function(){return 0!=this.Qa};r.cg=function(){this.Qa=0;this.Ac&&this.Ac.call(this.ya)};var Me=function(a){L.call(this);this.ya=a;this.c={}};z(Me,L);var Ne=[];r=Me.prototype;r.Ca=function(a,b,c,d){return this.Pg(a,b,c,d)};r.Pg=function(a,b,c,d,f){x(b)||(b&&(Ne[0]=b.toString()),b=Ne);for(var g=0;g<b.length;g++){var k=O(a,b[g],c||this.handleEvent,d||!1,f||this.ya||this);if(!k)break;this.c[k.key]=k}return this};r.zc=function(a,b,c,d){return this.je(a,b,c,d)};
r.je=function(a,b,c,d,f){if(x(b))for(var g=0;g<b.length;g++)this.je(a,b[g],c,d,f);else{a=Vc(a,b,c||this.handleEvent,d,f||this.ya||this);if(!a)return this;this.c[a.key]=a}return this};r.Rb=function(a,b,c,d,f){if(x(b))for(var g=0;g<b.length;g++)this.Rb(a,b[g],c,d,f);else c=c||this.handleEvent,d=Za(d)?!!d.capture:!!d,f=f||this.ya||this,c=Wc(c),d=!!d,b=Nc(a)?a.Na(b,c,d,f):a?(a=Yc(a))?a.Na(b,c,d,f):null:null,b&&(P(b),delete this.c[b.key]);return this};
r.Lb=function(){Gb(this.c,function(a,b){this.c.hasOwnProperty(b)&&P(a)},this);this.c={}};r.h=function(){Me.l.h.call(this);this.Lb()};r.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var Qe=function(a,b,c,d,f,g){if(F&&!Zb("525"))return!0;if(G&&f)return Oe(a);if(f&&!d)return!1;if(!E){typeof b==ya&&(b=Pe(b));var k=17==b||18==b||G&&91==b;if((!c||G)&&k||G&&16==b&&(d||g))return!1}if((F||Rb)&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(D&&d&&b==a)return!1;switch(a){case 13:return E?g||f?!1:!(c&&d):!0;case 27:return!(F||Rb||E)}return E&&(d||f||g)?!1:Oe(a)},Oe=function(a){if(48<=a&&57>=a||96<=a&&
106>=a||65<=a&&90>=a||(F||Rb)&&0==a)return!0;switch(a){case 32:case 43:case 63:case 64:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}},Pe=function(a){if(E)a=Re(a);else if(G&&F)switch(a){case 93:a=91}return a},Re=function(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};var Se=function(a,b){Q.call(this);a&&this.sd(a,b)};z(Se,Q);r=Se.prototype;r.ua=null;r.Db=null;r.vc=null;r.Eb=null;r.D=-1;r.oa=-1;r.ec=!1;
var Te={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},Ue={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Ve=!F||Zb("525"),We=G&&E;r=Se.prototype;
r.yg=function(a){(F||Rb)&&(17==this.D&&!a.ctrlKey||18==this.D&&!a.altKey||G&&91==this.D&&!a.metaKey)&&this.Be();-1==this.D&&(a.ctrlKey&&17!=a.keyCode?this.D=17:a.altKey&&18!=a.keyCode?this.D=18:a.metaKey&&91!=a.keyCode&&(this.D=91));Ve&&!Qe(a.keyCode,this.D,a.shiftKey,a.ctrlKey,a.altKey,a.metaKey)?this.handleEvent(a):(this.oa=Pe(a.keyCode),We&&(this.ec=a.altKey))};r.Be=function(){this.oa=this.D=-1};r.zg=function(a){this.Be();this.ec=a.altKey};
r.handleEvent=function(a){var b=a.va,c=b.altKey;if(D&&a.type==ta){var d=this.oa;var f=13!=d&&27!=d?b.keyCode:0}else(F||Rb)&&a.type==ta?(d=this.oa,f=0<=b.charCode&&63232>b.charCode&&Oe(d)?b.charCode:0):Qb&&!F?(d=this.oa,f=Oe(d)?b.keyCode:0):(d=b.keyCode||this.oa,f=b.charCode||0,We&&a.type==ta&&(c=this.ec),G&&63==f&&224==d&&(d=191));var g=d=Pe(d);d?63232<=d&&d in Te?g=Te[d]:25==d&&a.shiftKey&&(g=9):b.keyIdentifier&&b.keyIdentifier in Ue&&(g=Ue[b.keyIdentifier]);E&&Ve&&a.type==ta&&!Qe(g,this.D,a.shiftKey,
a.ctrlKey,c,a.metaKey)||(a=g==this.D,this.D=g,b=new Xe(g,f,a,b),b.altKey=c,this.dispatchEvent(b))};r.Ma=function(){return this.ua};r.sd=function(a,b){this.Eb&&this.detach();this.ua=a;this.Db=O(this.ua,ta,this,b);this.vc=O(this.ua,"keydown",this.yg,b,this);this.Eb=O(this.ua,"keyup",this.zg,b,this)};r.detach=function(){this.Db&&(P(this.Db),P(this.vc),P(this.Eb),this.Eb=this.vc=this.Db=null);this.ua=null;this.oa=this.D=-1};r.h=function(){Se.l.h.call(this);this.detach()};
var Xe=function(a,b,c,d){N.call(this,d);this.type="key";this.keyCode=a;this.charCode=b};z(Xe,N);var Ye={},Ze=null,$e=function(a){a=a[$a]||(a[$a]=++ab);delete Ye[a];Kb(Ye)&&Ze&&Ze.stop()},bf=function(){Ze||(Ze=new Le(function(){af(db())},20));var a=Ze;a.Bb()||a.start()},af=function(a){Gb(Ye,function(b){b.bh(a)});Kb(Ye)||bf()};var cf=function(){Q.call(this);this.eb=0;this.endTime=this.startTime=null};z(cf,Q);r=cf.prototype;r.Fh=function(){this.eb=1};r.Oe=function(){this.eb=0};r.ae=function(){return 1==this.eb};r.$d=function(){return-1==this.eb};r.be=function(){return 0==this.eb};r.dh=function(){this.S("begin")};r.pe=function(){this.S("end")};r.jh=function(){this.S("finish")};r.mh=function(){this.S("play")};r.qh=function(){this.S("resume")};r.rh=function(){this.S("stop")};r.S=function(a){this.dispatchEvent(a)};var df=function(a,b,c,d){cf.call(this);if(!x(a)||!x(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.cb=a;this.gg=b;this.duration=c;this.nd=d;this.coords=[];this.progress=0};z(df,cf);r=df.prototype;
r.play=function(a){if(a||this.be())this.progress=0,this.coords=this.cb;else if(this.ae())return!1;$e(this);this.startTime=a=db();this.$d()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.progress||this.dh();this.mh();this.$d()&&this.qh();this.Fh();var b=this[$a]||(this[$a]=++ab);b in Ye||(Ye[b]=this);bf();this.Bd(a);return!0};r.stop=function(a){$e(this);this.Oe();a&&(this.progress=1);this.Ve(this.progress);this.rh();this.pe()};
r.h=function(){this.be()||this.stop(!1);this.gh();df.l.h.call(this)};r.bh=function(a){this.Bd(a)};r.Bd=function(a){a<this.startTime&&(this.endTime=a+this.endTime-this.startTime,this.startTime=a);this.progress=(a-this.startTime)/(this.endTime-this.startTime);1<this.progress&&(this.progress=1);this.Ve(this.progress);1==this.progress?(this.Oe(),$e(this),this.jh(),this.pe()):this.ae()&&this.Yg()};
r.Ve=function(a){Ya(this.nd)&&(a=this.nd(a));this.coords=Array(this.cb.length);for(var b=0;b<this.cb.length;b++)this.coords[b]=(this.gg[b]-this.cb[b])*a+this.cb[b]};r.Yg=function(){this.S("animate")};r.gh=function(){this.S("destroy")};r.S=function(a){this.dispatchEvent(new ef(a,this))};var ef=function(a,b){M.call(this,a);this.coords=b.coords;this.y=b.coords[1];this.duration=b.duration;this.progress=b.progress};z(ef,M);var ff=function(a,b,c,d,f,g){function k(a){if(a){a.tabIndex=0;var b=l.zh;b?a.setAttribute("role",b):a.removeAttribute("role");Vd(a,"goog-zippy-header");l.eg(a);l.dg(a)}}Q.call(this);this.lc=f||Ac();this.Y=this.lc.Ma(a)||null;this.Ka=this.lc.Ma(d||null);this.Gb=Ya(b)?b:null;this.zh=g||"tab";this.T=this.Gb||!b?null:this.lc.Ma(b);this.P=1==c;u(c)||this.Gb||(this.Ka?this.P=this.Ka.style.display!=n:this.Y&&(this.P=Ud(this.Y,na)));this.ie=new Me(this);this.wc=new Se;this.ne=new Me(this);var l=this;k(this.Y);
k(this.Ka);this.Nb(this.P)};z(ff,Q);r=ff.prototype;r.h=function(){ff.l.h.call(this);Ic(this.ie);Ic(this.wc);Ic(this.ne)};r.collapse=function(){this.Nb(!1)};r.toggle=function(){this.Nb(!this.P)};r.Nb=function(a){this.T?Yd(this.T,a):a&&this.Gb&&(this.T=this.Gb());this.T&&Vd(this.T,"goog-zippy-content");this.Ka?(Yd(this.Y,!a),Yd(this.Ka,a)):this.Vc(a);this.Ie(a);this.dispatchEvent(new gf("toggle",this,this.P))};r.Ie=function(a){this.P=a};
r.Vc=function(a){if(this.Y){var b=this.Y;a?Vd(b,na):Wd(b,na);b=this.Y;a?Wd(b,ma):Vd(b,ma);b=this.Y;x(a)&&(a=a.join(" "));""===a||void 0==a?(Ke||(Ke={atomic:!1,autocomplete:n,dropeffect:n,haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:n,busy:!1,disabled:!1,hidden:!1,invalid:"false"}),a=Ke,"expanded"in a?b.setAttribute(ea,a.expanded):b.removeAttribute(ea)):b.setAttribute(ea,a)}};
r.dg=function(a){a&&(this.wc.sd(a),this.ie.Ca(this.wc,"key",this.lh))};r.eg=function(a){a&&this.ne.Ca(a,"click",this.kh)};r.lh=function(a){if(13==a.keyCode||32==a.keyCode)this.toggle(),this.Ed(a),a.preventDefault(),a.stopPropagation()};r.kh=function(a){this.toggle();this.Ed(a)};r.Ed=function(a){this.dispatchEvent(new gf("action",this,this.P,a))};var gf=function(a,b){M.call(this,a,b)};z(gf,M);var hf=function(a,b,c,d,f){d=d||Ac();var g=d.hc("DIV",{style:"overflow:hidden"});b=d.Ma(b);b.parentNode.replaceChild(g,b);g.appendChild(b);this.qb=g;this.I=null;ff.call(this,a,b,c,void 0,d,f);a=this.P;this.qb.style.display=a?"":n;this.Vc(a)};z(hf,ff);r=hf.prototype;r.animationDuration=500;r.Rf=function(a){return 1-Math.pow(1-a,3)};
r.Nb=function(a){if(this.P!=a||this.I){this.qb.style.display==n&&(this.qb.style.display="");var b=this.T.offsetHeight;if(this.I){a=this.P;cd(this.I);this.I.stop(!1);var c=b-Math.abs(parseInt(this.T.style.marginTop,10))}else c=a?0:b;this.Vc(a);this.I=new df([0,c],[0,a?b:0],this.animationDuration,this.Rf);O(this.I,["begin","animate","end"],this.Zg,!1,this);O(this.I,"begin",y(this.$g,this,a));O(this.I,"end",y(this.ah,this,a));this.I.play(!1)}};
r.Zg=function(a){var b=this.T;b.style.marginTop=a.y-b.offsetHeight+"px"};r.$g=function(a){this.dispatchEvent(new gf("a",this,a))};r.ah=function(a){a&&(this.T.style.marginTop="0");cd(this.I);this.Ie(a);this.I=null;a||(this.qb.style.display=n);this.dispatchEvent(new gf("toggle",this,a));this.dispatchEvent(new gf("b",this,a))};var jf=null;var V=new Ie;w("BLOG_CMT_LoggedInGaiaIdentity",Be,void 0);w("BLOG_CMT_NotLoggedInGaiaIdentityFactory",Ee,void 0);w("BLOG_CMT_NameUrlIdentityFactory",He,void 0);w("BLOG_CMT_AnonymousIdentityFactory",Gd,void 0);w("BLOG_CMT_onPost",function(){Je();return V.nh()},void 0);w("BLOG_CMT_onPreview",function(){return V.oh()},void 0);w("BLOG_CMT_onCommentBodyChange",function(){},void 0);w("BLOG_CMT_onCancel",function(){return V.eh()},void 0);w("BLOG_CMT_onSelectorChange",function(){return V.Ec()},void 0);
w("BLOG_CMT_onContinue",function(){return V.fh()},void 0);w("BLOG_CMT_onEdit",function(){return V.hh()},void 0);w("BLOG_CMT_addIdentity",function(a){return V.cc(a)},void 0);w("BLOG_CMT_addAndSelectIdentity",function(a){return V.od(a)},void 0);w("BLOG_CMT_addIdentityFactory",function(a){return V.pd(a)},void 0);w("BLOG_CMT_addNameUrlIdentityFactory",function(){return V.Of()},void 0);w("BLOG_CMT_addAnonIdentity",function(){return V.Nf()},void 0);
w("BLOG_CMT_addNotLoggedInGaiaIdentity",function(){return V.Pf()},void 0);w("BLOG_CMT_init",function(a,b){le(document.location.href);V.yh();V.Ec();V.ke();ze(a,b);K(Ea).value==Ja&&(K(Ea).value="false",qe(K(da),"previewMode"));ke();return!0},void 0);w("BLOG_CMT_createPhotoZippy",function(a,b){K(a)&&K(b)&&(jf=new hf(a,b))},void 0);w("BLOG_CMT_closePhotoZippy",function(){null!=jf&&jf.collapse()},void 0);
w("BLOG_CMT_finalizeBG",function(){window.ud&&window.ud.invoke(function(a){document.getElementById(fa).value=a})},void 0);
w("BLOG_CMT_getBG",function(){var a=new Hd("/comment-iframe-bg.g"),b=document.getElementById(fa).value;b&&a.Ob(fa,b);b=null;"Microsoft Internet Explorer"==window.navigator.appName&&(document.documentMode?b=document.documentMode:(b=5,document.compatMode&&"CSS1Compat"==document.compatMode&&(b=7)));b&&a.Ob("iemode",b);document.getElementById("pageID")&&a.Ob("page","1");Rd&&a.Ob("bgint",Rd);xd(a,function(){if(this.Xa()){var a=eval(this.pg());a instanceof Object&&a.length&&(1<a.length&&(eval(a[1]),Rd=
a[2]),window.ud=new botguard.bg(a[0]))}})},void 0);w("BLOG_CMT_setBG",function(a){Rd=a},void 0);w("BLOG_CMT_subscription.toggle",function(){if(!we){we=!0;var a=K("commentSubscriptionForm");xd(a.action,function(){we=!1;if(this.Xa()){var a=this.Rd();null!=a.errorMessage?U(3,a.errorMessage,!0):ne(a.statusMessage);ze(a.can_subscribe,a.is_subscribed)}else U(3,"\u0110\u00e3 x\u1ea3y ra l\u1ed7i khi k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7.",!0)},"POST",ve(a))}},void 0);
w("BLOG_CMT_showStatusMessage",ne,void 0);w("BLOG_CMT_showPostErrorMessage",function(a){U(4,a,!0)},void 0);w("BLOG_CMT_hidePreview",function(){Je();V.ab();je()},void 0);w("BLOG_xhr",R,void 0);R.send=xd;R.prototype.isSuccess=R.prototype.Xa;R.prototype.getResponseJson=R.prototype.Rd;w("$",K,void 0);function kf(a){return function(b){var c=-1;try{c=b.status}catch(d){}return 500<=c?(b.responseText.length?document.body.innerHTML=b.responseText:window.alert(LayoutsMessages.SERVER_ERROR),!1):a?a(b):!0}};var mf=function(a,b,c){var d=a.ownerDocument;b=b._GetHelper();var f=b._GetData(),g=c._GetAllData();a=lf(d,a,h,"widget-wrap1");a=lf(d,a,h,"widget-wrap2");a=lf(d,a,h,"widget-wrap3");var k=lf(d,a,h,"widget-content");if(a=f.version&&1<f.version)k.className+=" visibility",lf(d,k,h,"layout-widget-state "+(f.isVisible?"visible":"not-visible")).setAttribute("title",f.visibilityTooltipMessage);var l=lf(d,k,h,"layout-title");if(f[va]){var q=lf(d,k,h,ua);q.appendChild(d.createTextNode(f[va]));q.setAttribute("title",
f[ua])}l.appendChild(d.createTextNode(f["layout-title"]));f=lf(d,k,"a","editlink");var Z=b._GenerateWidgetMetadata();f.setAttribute("href",Z.quickEditUrl);f.target=ha;f.onclick=function(){return c._PopupConfig(d.getElementById(Z.instanceId))};a&&(f.className+=" icon");f.appendChild(d.createTextNode(g.messages.edit||"Edit"))},lf=function(a,b,c,d){a=a.createElement(c);a.className=d;b.appendChild(a);return a};var nf=function(){this.uh={};this.me={};this.Hc={};this.We=null;this.ve=[]};Va(nf);nf.prototype.Md=function(a,b){return a+"_"+b+".js"};var of=function(a){eval(a)};nf.prototype.Wd=function(a,b){w("__gjsload__",of,void 0);this.We=a.replace(/\.js$/,"");b&&(this.Md=b);hb(this.ve,function(a){this.Rg(a)},this);mb(this.ve)};nf.prototype.wh=function(a,b,c){var d=this.me,f=this.uh;d[a]||(d[a]={});if(c)d[a][b]=c;else if(f[a]){for(b=0;b<f[a].length;++b)(0,f[a][b][1])(d[a][f[a][b][0]]);delete f[a];delete this.Hc[a]}};
nf.prototype.Rg=function(a){rd(function(){if(!this.me[a]){var b=this.Md(this.We,a),c=Jb(this.Hc,b);this.Hc[a]=b;if(!c){c=Ec("SCRIPT",{type:"text/javascript"});var d=new gc;d.Mc=b;d instanceof gc&&d.constructor===gc&&d.If===fc?b=d.Mc:(Wa(d),b="type_error:TrustedResourceUrl");c.src=b;if(null===Ta){a:{b=t.document;if((b=b.querySelector&&b.querySelector("script[nonce]"))&&(b=b.nonce||b.getAttribute("nonce"))&&Sa.test(b))break a;b=null}Ta=b||""}(b=Ta)&&c.setAttribute("nonce",b);document.body.appendChild(c)}}},
0,this)};var pf=function(){this.J=[];this.N=[]};r=pf.prototype;r.Sg=function(){0==this.J.length&&(this.J=this.N,this.J.reverse(),this.N=[])};r.enqueue=function(a){this.N.push(a)};r.dequeue=function(){this.Sg();return this.J.pop()};r.o=function(){return this.J.length+this.N.length};r.isEmpty=function(){return 0==this.J.length&&0==this.N.length};r.clear=function(){this.J=[];this.N=[]};r.contains=function(a){return A(this.J,a)||A(this.N,a)};
r.remove=function(a){var b=this.J;var c=gb(b,a);0<=c?(Array.prototype.splice.call(b,c,1),b=!0):b=!1;return b||nb(this.N,a)};r.v=function(){for(var a=[],b=this.J.length-1;0<=b;--b)a.push(this.J[b]);var c=this.N.length;for(b=0;b<c;++b)a.push(this.N[b]);return a};var qf=function(a){this.j=new nd;a&&this.addAll(a)},rf=function(a){var b=typeof a;return b==p&&a||b==m?"o"+(a[$a]||(a[$a]=++ab)):b.substr(0,1)+a};r=qf.prototype;r.o=function(){return this.j.o()};r.add=function(a){this.j.set(rf(a),a)};r.addAll=function(a){a=pd(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};r.Lb=function(a){a=pd(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};r.remove=function(a){return this.j.remove(rf(a))};r.clear=function(){this.j.clear()};r.isEmpty=function(){return this.j.isEmpty()};
r.contains=function(a){return this.j.ha(rf(a))};r.v=function(){return this.j.v()};r.clone=function(){return new qf(this)};r.ac=function(){return this.j.ac(!1)};var sf=function(a,b){L.call(this);this.le=a||0;this.Ib=b||10;if(this.le>this.Ib)throw Error("[goog.structs.Pool] Min can not be greater than max");this.U=new pf;this.da=new qf;this.delay=0;this.xc=null;this.jb()};z(sf,L);r=sf.prototype;r.tb=function(){var a=db();if(!(null!=this.xc&&a-this.xc<this.delay)){var b=this.xh();b&&(this.xc=a,this.da.add(b));return b}};r.Oc=function(a){return this.da.remove(a)?(this.bc(a),!0):!1};
r.xh=function(){for(var a;0<this.Ld()&&(a=this.U.dequeue(),!this.Dc(a));)this.jb();!a&&this.o()<this.Ib&&(a=this.ic());return a};r.bc=function(a){this.da.remove(a);this.Dc(a)&&this.o()<this.Ib?this.U.enqueue(a):this.kc(a)};r.jb=function(){for(var a=this.U;this.o()<this.le;)a.enqueue(this.ic());for(;this.o()>this.Ib&&0<this.Ld();)this.kc(a.dequeue())};r.ic=function(){return{}};r.kc=function(a){if(typeof a.ia==m)a.ia();else for(var b in a)a[b]=null};r.Dc=function(a){return typeof a.Uf==m?a.Uf():!0};
r.contains=function(a){return this.U.contains(a)||this.da.contains(a)};r.o=function(){return this.U.o()+this.da.o()};r.kg=function(){return this.da.o()};r.Ld=function(){return this.U.o()};r.isEmpty=function(){return this.U.isEmpty()&&this.da.isEmpty()};r.h=function(){sf.l.h.call(this);if(0<this.kg())throw Error("[goog.structs.Pool] Objects not released");delete this.da;for(var a=this.U;!a.isEmpty();)this.kc(a.dequeue());delete this.U};var tf=function(a,b){this.he=a;this.Zc=b};tf.prototype.getKey=function(){return this.he};tf.prototype.clone=function(){return new tf(this.he,this.Zc)};var uf=function(a){this.L=[];a&&this.Gg(a)};r=uf.prototype;r.Yd=function(a,b){var c=this.L;c.push(new tf(a,b));this.Xg(c.length-1)};r.Gg=function(a){if(a instanceof uf){var b=a.K();a=a.v();if(0>=this.o()){for(var c=this.L,d=0;d<b.length;d++)c.push(new tf(b[d],a[d]));return}}else b=Ib(a),a=Hb(a);for(d=0;d<b.length;d++)this.Yd(b[d],a[d])};r.remove=function(){var a=this.L,b=a.length,c=a[0];if(!(0>=b))return 1==b?mb(a):(a[0]=a.pop(),this.Ug(0)),c.Zc};
r.Ug=function(a){for(var b=this.L,c=b.length,d=b[a];a<c>>1;){var f=this.ng(a),g=this.rg(a);f=g<c&&b[g].getKey()<b[f].getKey()?g:f;if(b[f].getKey()>d.getKey())break;b[a]=b[f];a=f}b[a]=d};r.Xg=function(a){for(var b=this.L,c=b[a];0<a;){var d=this.og(a);if(b[d].getKey()>c.getKey())b[a]=b[d],a=d;else break}b[a]=c};r.ng=function(a){return 2*a+1};r.rg=function(a){return 2*a+2};r.og=function(a){return a-1>>1};r.v=function(){for(var a=this.L,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].Zc);return b};
r.K=function(){for(var a=this.L,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].getKey());return b};r.ha=function(a){return kb(this.L,function(b){return b.getKey()==a})};r.clone=function(){return new uf(this)};r.o=function(){return this.L.length};r.isEmpty=function(){return 0==this.L.length};r.clear=function(){mb(this.L)};var vf=function(){uf.call(this)};z(vf,uf);vf.prototype.enqueue=function(a,b){this.Yd(a,b)};vf.prototype.dequeue=function(){return this.remove()};var wf=function(a,b){this.Dd=void 0;this.Mb=new vf;sf.call(this,a,b)};z(wf,sf);r=wf.prototype;r.tb=function(a,b){if(!a)return(a=wf.l.tb.call(this))&&this.delay&&(this.Dd=t.setTimeout(y(this.vb,this),this.delay)),a;this.Mb.enqueue(u(b)?b:100,a);this.vb()};r.vb=function(){for(var a=this.Mb;0<a.o();){var b=this.tb();if(b)a.dequeue().apply(this,[b]);else break}};r.bc=function(a){wf.l.bc.call(this,a);this.vb()};r.jb=function(){wf.l.jb.call(this);this.vb()};
r.h=function(){wf.l.h.call(this);t.clearTimeout(this.Dd);this.Mb.clear();this.Mb=null};var xf=function(a,b,c,d){this.pc=a;this.W=!!d;wf.call(this,b,c)};z(xf,wf);xf.prototype.ic=function(){var a=new R,b=this.pc;b&&b.forEach(function(b,d){a.headers.set(d,b)});this.W&&a.Sc(!0);return a};xf.prototype.Dc=function(a){return!a.ta&&!a.Bb()};var yf=function(a,b,c,d,f,g){Q.call(this);this.Cc=u(a)?a:1;this.ra=u(f)?Math.max(0,f):0;this.W=!!g;this.Ga=new xf(b,c,d,g);this.M=new nd;this.rb=new Me(this)};z(yf,Q);var zf=[Aa,e,Ia,"error","abort","timeout"];r=yf.prototype;r.Rc=function(a){this.ra=Math.max(0,a)};r.send=function(a,b,c,d,f,g,k,l,q,Z){if(this.M.get(a))throw Error("[goog.net.XhrManager] ID in use");b=new Af(b,y(this.xg,this,a),c,d,f,k,u(l)?l:this.Cc,q,u(Z)?Z:this.W);this.M.set(a,b);a=y(this.ug,this,a);this.Ga.tb(a,g);return b};
r.abort=function(a,b){var c=this.M.get(a);if(c){var d=c.Tb;c.Bh(!0);b&&(d&&(this.ze(d,c.$c),Vc(d,Aa,function(){this.Ga.Oc(d)},!1,this)),this.M.remove(a));d&&d.abort()}};r.ug=function(a,b){var c=this.M.get(a);c&&!c.Tb?(this.Qf(b,c.$c),b.Rc(this.ra),b.Eh(c.Ea),b.Sc(c.W),c.Tb=b,this.dispatchEvent(new Bf(Aa,this,a,b)),this.Ce(a,b),c.md&&b.abort()):this.Ga.Oc(b)};
r.xg=function(a,b){var c=b.target;switch(b.type){case Aa:this.Ce(a,c);break;case e:return this.vg(a,c,b);case Ia:this.Ag(a,c);break;case "timeout":case "error":this.wg(a,c);break;case "abort":this.tg(a,c)}return null};r.Ce=function(a,b){var c=this.M.get(a);!c||c.zd||c.oc()?(c&&(this.ze(b,c.$c),this.M.remove(a)),this.Ga.Oc(b)):(c.Fg(),b.send(c.getUrl(),c.Tg,c.getContent(),c.pc))};
r.vg=function(a,b,c){var d=this.M.get(a);if(7==b.Ba||b.Xa()||d.oc())if(this.dispatchEvent(new Bf(e,this,a,b)),d&&(d.Ch(!0),d.yd))return d.yd.call(b,c);return null};r.tg=function(a,b){this.dispatchEvent(new Bf("abort",this,a,b))};r.Ag=function(a,b){this.dispatchEvent(new Bf(Ia,this,a,b))};r.wg=function(a,b){this.M.get(a).oc()&&this.dispatchEvent(new Bf("error",this,a,b))};r.ze=function(a,b,c){this.rb.Rb(a,c||zf,b)};r.Qf=function(a,b,c){this.rb.Ca(a,c||zf,b)};
r.h=function(){yf.l.h.call(this);this.Ga.ia();this.Ga=null;this.rb.ia();this.rb=null;this.M.clear();this.M=null};var Bf=function(a,b,c,d){M.call(this,a,b);this.id=c;this.Tb=d};z(Bf,M);var Af=function(a,b,c,d,f,g,k,l,q){this.Ih=a;this.Tg=c||"GET";this.Xf=d;this.pc=f||null;this.Cc=u(k)?k:1;this.td=0;this.md=this.zd=!1;this.$c=b;this.yd=g;this.Ea=l||"";this.W=!!q;this.Tb=null};r=Af.prototype;r.getUrl=function(){return this.Ih};r.getContent=function(){return this.Xf};r.Fg=function(){this.td++};
r.oc=function(){return this.td>this.Cc};r.Ch=function(a){this.zd=a};r.Bh=function(a){this.md=a};function Cf(a,b,c,d,f,g){this.Ua=a;this.Fe=b;this.Ee=d||null;this.data=f||null;if(g){if(this.jc=g,"displayModeSnippet"!=g&&"displayModeFull"!=g&&g!=ja&&g!=ka)throw"bad display mode: "+g;}else this.jc=ka;this.Cb=!1}Cf.prototype.mg=function(){return this.Ua};function Df(a){this.ag=!0;this.A=a;this.Sb=null}r=Df.prototype;r.Gf=function(a){this.Sb=a};r.ff=function(){return this.A.data};r.Bf=function(a){return this.A.data=a};r.Df=function(a){return this.A.Cb=a};
r.cf=function(){var a={};a.type=this.Sb.Te;a.instanceId=this.A.Ua;a.sectionId=this.A.Fe;a.actionUrl=W.fc;a.quickEditUrl=W.Hd+"&widgetType="+this.Sb.Te+"&widgetId="+this.A.Ua+"&sectionId="+this.A.Fe+"&action="+W.cd;return a};r.$b=function(a,b,c,d){b=b||{};window.__wavt&&(b.xssi_token=window.__wavt);W.$b(a,b,this.A.Ua,this.Sb.Te,c,d)};function W(){}W.kf=function(a,b,c){W.fa={};W.Hd=a;W.fc=b;W.Sh=c;W.Oa={};W.Ub=new yf;W.oe=0;W.Ic=0;O(W.Ub,Aa,function(){W.Ic++});O(W.Ub,e,function(){W.Ic--})};
W.Jf=function(a){a=W.$e(a.document);document.body.appendChild(a)};W.Hf=function(a){W.Jf(window);if(window.parent==window){var b="Preview";a&&(b=a);a=W.Ze(window.document,b);document.body.appendChild(a[0]);document.body.appendChild(a[1])}};W.mf=ha;W.Ye=ha;W.cd="editWidget";W.ef=function(){return W.fc};W.Ef=function(a,b){W.Fc=a;W.th=b};W.hf=function(){return W.Fc};W.Ff=function(a){W.Kh=a};W.dd=function(){return W.Kh};W.Cf=function(a){W.Oa=a};
W.df=function(){var a={},b;for(b in W.Oa){var c=W.Oa[b];a[c.name]=c.data}c={};for(b in W.fa)c[b]=W.fa[b].w.A.data;a.widgets=c;return a};W.fd=function(a,b){var c=new Df(b);a=new window[a](c);c.Gf(a);W.fa[b.Ua]=a;W.bd(a);return a};W.tf=function(a,b){a=W.fd(a,b);a.w.Df(!0);return a};W.bd=function(a){a.w.A.jc!=ka&&(a.w.ag=!1)};W.sa=function(a){return W.fa?W.fa[a]:null};
W.Zb=function(a,b,c,d,f){var g="";d&&(g="&widgetId="+d);a=W.Hd+"&action="+a+"&sectionId="+b+"&widgetType="+c+g;if(window.name==f)return window.location.replace(a),window.focus(),window;f=window.open(a,f,"width=570,height=600,left=75,top=20,resizable=yes,scrollbars=yes");f.focus();return f};
W.rf=function(a){var b=a.getAttribute("id"),c=W.sa(b);if(c){var d=c.w.Ja;if(null!=d&&!d.closed)return d.focus(),!1}d="config"+b;a=W.Zb(W.cd,a.parentNode.getAttribute("id"),a.getAttribute("widgetType"),b,d);c&&(c.w.Ja=a);return!1};W.sf=function(a){W.Zb(W.Ye,a.parentNode.getAttribute("id"),a.getAttribute("widgetType"),a.getAttribute("id"),W.mf);return!1};W.af=function(a,b,c){W.ga(c,c.LayoutsMessages.DELETING);W.hd("delete",{},a,b)};
Df.prototype.yf=function(a,b){W.ga(b,b.LayoutsMessages.SAVING);this.$b("configure",a)};W.zf=function(a,b,c){a.sectionid=document.getElementById("sectionId").value;W.ga(c,c.LayoutsMessages.SAVING);W.hd("addnew",a,"",b)};W.Nh=function(a,b,c){b=W.sa(b);b.w.A.Cb?W.zf(a,c,window):b.w.yf(a,window)};W.$b=function(a,b,c,d,f,g){W.gd(W.fc,a,b,c,d,f,g)};W.hd=function(a,b,c,d,f){W.Fc&&(b.security_token=W.th,W.gd(W.Fc,a,b,c,d,f))};
W.gd=function(a,b,c,d,f,g,k){b=["action="+encodeURIComponent(b),"widgetId="+encodeURIComponent(d),"widgetType="+encodeURIComponent(f),"responseType=js"];for(var l in c)if(typeof c[l]==p)for(d=c[l],f=0;f<d.length;++f)b.push(encodeURIComponent(l)+"="+encodeURIComponent(d[f]));else b.push(encodeURIComponent(l)+"="+encodeURIComponent(c[l]));var q=g||kf();c=function(){q(this.a)&&window.eval(this.qg())};"GET"==k?(a=0<=a.indexOf("?")?a+"&":a+"?",W.Ub.send(""+W.oe++,a+b.join("&"),"GET",void 0,null,null,c)):
W.Ub.send(""+W.oe++,a,"POST",b.join("&"),null,null,c)};W.Af=function(a,b){a&&(a=W.sa(a))&&(a.w.Ja=b)};W.hb=function(a,b){0==W.Ic?a.setTimeout(function(){a.close()},b):a.setTimeout(function(){W.hb(a,b)},200)};W.lf=function(a,b){a&&(W.hb(a,100),W.Kf(a,b))};W.Kf=function(a,b){if(a){var c=a.document.getElementById(Ga);c&&(c=c.innerHTML);c&&a&&a.opener.parent&&a.opener.parent.editor&&a.opener.parent.editor.SetSaveMessage(c,b)}};
W.ed=function(a,b,c){a=W.fa[a];if(null!=c.errors){var d=a?a.w.Ja:null;d||(d=window);W.ga(d,c.errors);a&&a.ib?a.ib(b,c,d):W.ib(c,d)}else a.ed(b,c)};W.ib=function(a,b){a=a["error-details"];for(var c in a)Ef(c,a[c],b.document)};W.nf=function(a,b){window.parent&&window.parent.editor&&b?W.pf(a,b):window.location.replace(window.location.href)};W.pf=function(a,b){var c=W.sa(a);c.w.Bf(b.data);a=document.getElementById(a);Hc(a);mf(a,c,W);c.w.Ja=null};
W.jf=function(a,b,c){var d=c[Fa];if(null!=c.errors)W.ga(window,c.errors),W.ib(c,window);else if("addnew"==b){if(W.Xb(window)){if(window.opener&&window.opener.parent)var f=window.opener.parent;f&&f.editor&&f.editor.HandleAddNewWidget(c)}W.ga(window,d);null==window.opener?(a=window.location,b="/rearrange?blogID="+c.blogID,b instanceof H||b instanceof H||(b=typeof b==p&&b.ma?b.ca():String(b),jc.test(b)||(b=ca),b=kc(b)),a.href=ic(b)):f&&f._WidgetManager?f._WidgetManager._KillPopupDelay(window):W.hb(window,
100)}else c=W.fa[a],"delete"==b&&(W.ga(c.w.Ja,d),W.bf(a,"_OnWidgetDeleted"))};W.qf=function(a){var b=W.sa(a);b&&(b.w.A.jc==ja?top.editor.HandleDeleteWidget(b.w.A.Ee):(b=b.w.A.Ee,b.parentNode.removeChild(b)),delete W.fa[a])};W.bf=function(a,b,c){if(W.Xb(window)){var d=window.opener;c||(c=d._WidgetManager[b]);c(a);d._WidgetManager?d._WidgetManager._KillPopupDelay(window,a):W.hb(window,100)}else a=W.dd()+"?widgetId="+a,a+="&func="+encodeURIComponent(b),window.location.replace(a)};
W.Xb=function(a){var b=!1;try{if(a.opener){var c="X"+a.opener.document.domain;c&&"X"!=c&&(b=!0)}}catch(d){}return b};W.jd="status-msg-yellow-on-white";W.ga=function(a,b){a||(a=self);var c=a.document.getElementById(Ga);c&&(c.innerHTML=b);(a=a.document.getElementById(Fa))&&qe(a,W.jd)};W.Lh=function(a){a||(a=self);(a=a.document.getElementById(Fa))&&se(a,W.jd)};W.Mh=function(a){a&&0<a.length&&"http"!=a.substring(0,4)&&(a="http://"+a);return a};
W.gf=function(a,b){if(A(pe(a),b))return a;if(a)for(var c=a.childNodes.length,d=0;d<c;d++){var f=W.gf(a.childNodes.item(d),b);if(f)return f}return null};
W.$e=function(a){a=a.createElement(h);a.className="blogger-clickTrap singleton-element";a.style.position="fixed";a.style.top="0";a.style.left="0";a.style.width="100%";a.style.height="100%";D&&!Zb(7)&&(a.style.height="expression(this.parentNode.clientHeight)");a.style.zIndex="1000";a.style.cursor="default";a.onclick=W.Yb;a.onmousedown=W.Yb;a.onmouseup=W.Yb;a.style.background="white";a.style.filter="alpha(opacity=1)";a.style.opacity=".01";a.innerHTML="&nbsp;";return a};
W.Ze=function(a,b){var c=W.ad(a,b);a=W.ad(a,b);c.style.backgroundColor="#000";c.style.border="1px solid #aaa";D&&(c.style.filter=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678) alpha(opacity=50)');c.style.opacity=".5";a.style.border="1px solid transparent";c.style.zIndex=1200;a.style.zIndex=1200;return[c,a]};
W.ad=function(a,b){a=a.createElement(h);a.style.position="absolute";a.style.top="75px";a.style.left="-225px";a.style.width="600px";a.style.height="28px";a.style.margin="0";a.style.padding="10px";a.style.fontSize="24px";a.style.textAlign="center";a.style.color="#fff";a.style.fontFamily='"trebuchet ms",verdana,arial,sans-serif';D&&(a.style.top="-140px",a.style.left="-140px",a.style.filter=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678)');
a.style.MozTransform=Ba;a.style.MozTransformOrigin="50% 0";a.style.WebkitTransform=Ba;a.style.WebkitTransformOrigin="50% 0";a.innerHTML=b;a.className="singleton-element";return a};W.Qh=function(a){for(var b in W.Oa){var c=W.Oa[b];if(c&&"features"==c.name)return c.data[a]==Ja}return!1};W.Yb=function(a){a||(a=window.event);a&&(a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation());return!1};
var Ff=function(a,b){b||(b=document);return b.getElementById("errormessage_"+a)},Gf=function(a){if(a=Ff(a))Hc(a),a.className="errorbox-good"},Ef=function(a,b,c){if(a=Ff(a,c))a.innerHTML=b,a.className="errorbox-bad errormsg"};w("_WidgetManager",W,void 0);W._Init=W.kf;W._SetPageActionUrl=W.Ef;W._GetPageActionUrl=W.hf;W._SetWidgetRefreshUrl=W.Ff;W._GetWidgetRefreshUrl=W.dd;W._GetCallbackUrl=W.ef;W._DeleteWidgetFromPage=W.af;W._DisplayWidget=W.bd;W._GetWidget=W.sa;W._HandleControllerResult=W.ed;
W._HandlePageActionResult=W.jf;W._IsOpenerReachable=W.Xb;W._SetConfigWin=W.Af;W._SetDataContext=W.Cf;W._SetupPreview=W.Hf;W._RegisterWidget=W.fd;W._RegisterNewWidget=W.tf;W._PopupPaneFromParams=W.Zb;W._PopupConfig=W.rf;W._PopupToolbox=W.sf;W._KillPopupDelay=W.lf;W._OnWidgetConfigured=W.nf;W._OnWidgetDeleted=W.qf;w("_WidgetInfo",Cf,void 0);Cf.prototype._getInstanceId=Cf.prototype.mg;Df.prototype._GetData=Df.prototype.ff;Df.prototype._GenerateWidgetMetadata=Df.prototype.cf;W._GetAllData=W.df;
w("widget_module_provide",function(a,b,c){nf.lg().wh(a,b,c)},void 0);function X(a,b,c,d,f,g,k,l){this.C=a;this.vd="null"!=b?b:null;this.fe=c;this.de=d;this.ee=f;this.Ge=g;this.ge=k;this.Ah=l;this.yb=this.za=-1;this.rc=null;this.$a=300;this.Bc="200px";this.H=document.getElementById(this.C+"_picImg");this.mb=document.getElementById(this.C+"_changeImageLink");this.xb=document.getElementById(this.C+"_imageChoiceTable");this.sc=document.getElementById(this.C+"_imgSrcFromPCRadio");this.Vd=document.getElementById(this.C+"_imgSrcFromWebRadio");this.f=document.getElementById(this.C+
"_imgFileNameInput");this.Ra=document.getElementById(this.C+"_imgUrlTextInput");this.rd=window.frames[this.C+"_asynchronousFileUploadIframe"];this.qc=0;this.s=new Image;this.s.onload=y(this.sh,this);this.s.onerror=y(this.ih,this);this.Jd=!1;this.wa=this.u=this.Fb=null;this.Nc=!1}r=X.prototype;
r.sh=function(){this.qc=0;Gf(this.C+ba);Gf(this.C+aa);this.sc.checked&&0!=this.za||(this.za=this.s.width,this.yb=this.s.height,this.rc=this.s.src);var a=1,b=1;this.s.width>this.$a&&(a=this.$a/this.s.width);this.s.height>this.$a&&(b=this.$a/this.s.height);a=Math.min(a,b);this.H.style.width=Math.round(this.s.width*a)+"px";this.H.style.height=Math.round(this.s.height*a)+"px";this.H.src=this.s.src;this.H.style.display="";this.xb.style.display=n;this.mb.style.display="";this.f.disabled=!0;this.fe&&this.fe.call({},
this.H.src,this.rc,this.za,this.yb)};r.bb=function(a,b,c,d){a?(Ef(this.C+aa,b),Gf(this.C+ba)):(Ef(this.C+ba,b),Gf(this.C+aa));this.H.style.display=n;this.xb.style.display="";this.mb.style.display=n;this.f.disabled=!1;this.de&&this.de.call({},c,d)};r.ih=function(){if(2>this.qc){this.qc++;var a=this.s.src;this.s.src="";this.Ya(a)}else this.bb(this.sc.checked,WidgetMessages.SIV_INVALID_URL,this.H.src,[])};r.Ya=function(a){this.Re();this.s.src=a};
r.Vf=function(a){a=a||window.event;window.event?(a.returnValue=!1,a.cancelBubble=!0):(a.preventDefault(),a.stopPropagation());this.H.style.display=n;this.mb.style.display=n;this.xb.style.display="";this.f.disabled=!1;this.Ra.value="";this.Ae();this.Nc=!0;this.ee&&this.ee.call({})};r.Dg=function(){this.sc.checked=Ja;this.Ra.value="";this.Re();this.Wg();this.Jd=!0;try{this.u.submit()}catch(a){this.bb(!0,WidgetMessages.SIV_INVALID_URL,this.u.value,[])}this.Vg()};
r.gc=function(){var a=this.rd.document.result;if(a)if(a.hasErrors)0<a.errors.length?this.bb(!0,a.errors[0].message,this.f.value,a.errors):this.bb(!0,WidgetMessages.SIV_INVALID_URL,this.f.value,a.errors);else{var b=Math.max(a.origWidth,a.origHeight),c=this.Td();0!=this.za&&-1!=c&&b>c?(b=c/b,this.za=Math.round(a.origWidth*b),this.yb=Math.round(a.origHeight*b)):(this.za=a.origWidth,this.yb=a.origHeight);this.rc=a.mainSrc;this.Ya(a.thumbSrc)}else this.bb(!0,WidgetMessages.SIV_INVALID_URL,this.f.value,
[])};r.Eg=function(a){9!=(a||window.event).keyCode&&(this.Vd.checked=Ja,null!=this.Fb&&(window.clearTimeout(this.Fb),this.Fb=null),a=y(this.Og,this),this.Fb=window.setTimeout(a,1E3))};r.Og=function(){if(this.Nc||this.s.src!=this.Ra.value)this.Ae(),this.Ya(this.Ra.value);this.Nc=!1};r.Qg=function(a){this.Vd.checked=!0;this.Ra.value=a;this.Ya(a)};
r.Re=function(){this.H.src="https://resources.blogblog.com/img/icon_inprogress.gif";this.H.style.width=this.Bc;this.H.style.height=this.Bc;this.H.style.display="";this.xb.style.display=n;this.mb.style.display=n};
r.Wg=function(){if(!this.u){this.u=document.createElement("form");this.u.action="imageUpload.do";this.u.method="POST";this.u.target=this.rd.name;this.u.encoding="multipart/form-data";this.u.style.display=n;if(this.vd){var a=document.createElement(sa);a.type=oa;a.name="blogID";a.value=this.vd;this.u.appendChild(a)}a=document.createElement(sa);a.type=oa;a.name=Ca;a.id=Ca;this.u.appendChild(a);a=document.createElement(sa);a.type=oa;a.name="security_token";a.value=this.Ah;this.u.appendChild(a);document.body.appendChild(this.u)}a=
this.Td();-1==a&&(a=1600);document.getElementById(Ca).value=a;this.wa={parent:this.f.parentNode,nextSibling:this.f.nextSibling};this.f.parentNode.removeChild(this.f);this.u.appendChild(this.f)};r.Dh=function(a){this.$a=a;this.Bc=a+"px"};r.Vg=function(){this.u.removeChild(this.f);this.wa&&this.wa.nextSibling?this.wa.parent.insertBefore(this.f,this.wa.nextSibling):this.wa.parent.appendChild(this.f)};
r.Ae=function(){var a=document.createElement(sa);a.type="file";a.name=this.f.name;a.id=this.f.id;a.onchange=this.f.onchange;var b=this.f.nextSibling;null==b?this.f.parentNode.appendChild(a):this.f.parentNode.insertBefore(a,b);this.f.parentNode.removeChild(this.f);this.f=a};r.Td=function(){return-1==this.Ge&&this.ge?this.ge():this.Ge};function Y(){this.Yc={}}var Hf=new Y;Y.prototype.Yf=function(a,b,c,d,f,g,k,l){this.Yc[a]=new X(a,b,eval(c),eval(d),eval(f),g,eval(k),l);return this.Yc[a]};
Y.prototype.Sd=function(a){return this.Yc[a]};Y.prototype.gc=function(a){(a=this.Sd(a))&&a.Jd&&a.gc()};w("_UploadSimpleImage",Hf,void 0);Y.prototype._createUsiContainer=Y.prototype.Yf;Y.prototype._getUsiContainer=Y.prototype.Sd;Y.prototype._channelResultArrived=Y.prototype.gc;X.prototype._changeImage=X.prototype.Vf;X.prototype._imgUrlFileOnChange=X.prototype.Dg;X.prototype._imgUrlTextOnKeyUp=X.prototype.Eg;X.prototype._loadInitialUrl=X.prototype.Qg;X.prototype._loadImageFromUrl=X.prototype.Ya;
X.prototype._setPreviewSize=X.prototype.Dh;}).call(this);
